### PR TITLE
Set +x attribute for files in software section

### PR DESCRIPTION
**Pull request by Baguage**
Proposing fix for #1171

### CODE REVIEW

**Comment by dthain** [comment]
@hmeng-19 please let us know if this PR makes sense.

**Comment by hmeng-19** [comment]
@dthain , I am waiting for the feedback from Alex about my suggestion about #1171 .

**Comment by hmeng-19** [comment]
BTW, I do not think it should be Umbrella's duty to set any file permission. The file permission should be preserved when a user archives a package. Umbrella tries to maintain the file permission as much as possible.

**Comment by dthain** [comment]
@hmeng this pull request has been outstanding for a while now.  Please decide whether we should accept this in the current form, or solve the problem in a different way.

**Comment by hmeng-19** [comment]
@Baguage , I have trouble to reproduce the problem you have. You can show me the problem when I am back. Then we can review this PR. Sounds good?

**Comment by hmeng-19** [comment]
@dthain , I would leave the PR for now. I am also okay if you want to close it for now.

**Comment by dthain** [comment]
Let me propose an alternate approach to this:

I think the underlying issue here is that a remote storage system will not necessary record the desired permissions bits associated with a file.  If Umbrella downloads a given file, it will be given mode bits according to the current umask, which isn't necessarily what the user wants.  And, while some items from software should be marked as executable, that won't always be the case.

So, let me suggest an alternate:

Umbrella should accept a `mode` field wherever a file can be specified.  If the permissions are important for a particular file, then the user can do something like this:

```
source: "http://....",
checksum: abc123...,
mode: 0755
```
Umbrella can easily look for that an set it, and then user only needs to give it if it is significant.

What do you think?

**Comment by hmeng-19** [comment]
@dthain , a software dependency pointed by the `source` field is usually a directory, not a single file.

**Comment by Baguage** [comment]
@dthain - that sounds like a good idea. As @hmeng-19 pointed out "mode" is only applicable for "plain" format.
If we are on the same page with the solution, I can update my pull request with the support for "mode" option.

**Comment by hmeng-19** [comment]
@Baguage , sounds good. Go ahead.

**Comment by dthain** [comment]
This pull request has been open for many months now.
Is it still in progress, or should I close it?

**Comment by hmeng-19** [comment]
@dthain , you can close this one for now.
I will work on a new PR today to implement your suggestion: adding a new field, `mode` to specify the file mode.

**Comment by hmeng-19** [comment]
@dthain, @Baguage  , please see #1579 .

**Pull request closed without merging**
