### PR TITLE
Adds new Makeflow example using packaged executable

### PR DESCRIPTION
**Pull request by nkremerh**
Addresses #1149.

This example makeflow  has four general steps:
locally curl needed text files, starch the local /usr/bin/perl, run a perl script over the text files, gather results to output final result.

@btovar, mind taking another look at this?

### CODE REVIEW

**Comment by dthain** [comment]
How about the JX equivalent?

**Comment by dthain** [comment]
Sorry, I just noticed that this is a pull against cctools.
Why not add this to makeflow-examples instead?
https://github.com/cooperative-computing-lab/makeflow-examples

**Comment by btovar** [comment]
I'm fine with either/both.

**Comment by nkremerh** [comment]
I was under the impression this was intended to replace the current Makeflow example in CCTools proper. Please let me know the most appropriate place for this. I will add in a JX version soon.

**Comment by dthain** [comment]
Good, I think that does a good job of conveying how JX can help with the representation.

One thing I don't understand -- it looks like you are using starch multiple times to combine the perl script with the perl executable _and_ the individual input files.  

Why not just use starch once to combine the script with perl, and send the input files individually?  (That way the starched perl can be cached.)

**Comment by nkremerh** [comment]
@dthain, good point! It was my impression starch required a specific command to create a .sfx archive. Since each task specified a unique file to be read by the perl script, I figured I would need to create a unique .sfx for each task which uses perl. I will take another look at it.

**Comment by nkremerh** [comment]
@dthain @btovar Do we want this in CCTools or the Makeflow Examples repository?

**Comment by dthain** [comment]
Makeflow examples, please.
I don't think anyone finds the examples in the current location, and so we should work on moving those as well...

**Comment by nkremerh** [comment]
I will close this pull request and move this to the examples repository.

**Pull request closed without merging**
