### PR TITLE
Vine: Peer Transfer Fixups

### PR DESCRIPTION
**Pull request by colinthomas-z80**
Initial work on issue #3282 

Normal input files sent by the manager are properly considered for peer transfers now

### CODE REVIEW

**Comment by dthain** [comment]
That change makes sense to me.  Do peer transfers also work for mini-tasks and temporary files?  Those work a little differently b/c they originate at a worker and not at the manager.

**Comment by colinthomas-z80** [comment]
Mini tasks still need additional work. Temp files are good to go.

**Comment by dthain** [comment]
RTM?

**Comment by colinthomas-z80** [comment]
@dthain still working on an issue, also have to add python bindings and document

**Review by dthain — CHANGES_REQUESTED** [review]
I can see `remove_one_manager` but it doesn't seem to get called anywhere.  Am I missing something?

**Comment by colinthomas-z80** [comment]
@dthain I had originally used that as a way of adding/removing a manager entry to the transfer table, but later on I figured tracking the manager transfers was just unnecessary overhead since we are only making sequential transfers anyway.

**Review by dthain — APPROVED** [review]
Make sure you link and  close the relevant issue.

**Review by btovar — CHANGES_REQUESTED** [review]
Please remove the function duplicates from manager.py

**Review by btovar — APPROVED** [review]

**Pull request merged**
