### PR TITLE
Makeflow condor logs

### PR DESCRIPTION
**Pull request by btovar**
Generate output and error files in the submit file:

RULENUMBER.condor.error and RULENUMBER.condor.output.

### CODE REVIEW

**Comment by dthain** [comment]
Hmm, I'm not thrilled with this approach, since it seems to be adding yet another special case to behavior that is already inconsistent within the batch job interface.

Can we step back and consider if there is a more consistent way that stderr could be handled through the batch job interface?

**Comment by btovar** [comment]
What about this one instead?

makeflow --error-dir=somedir

Error files are written to somedir, for batch systems that support it (right now only condor implemented). The targer error file is passed as an argument to submit job.

**Comment by dthain** [comment]
Let's talk about it.

**Comment by nhazekam** [comment]
@btovar Has this been resolved? Is it still a priority for 5.5?

**Comment by btovar** [comment]
Not resolved yet.  A clean solution won't be ready for 5.5.

**Comment by nhazekam** [comment]
As this is not going to be resolved currently I am removing myself as an assignee.

**Pull request closed without merging**
