### PR TITLE
Use new libcvmfs interface if available

### PR DESCRIPTION
**Pull request by trshaffer**
@jblomer added a new interface for option handling and initialization for libcvmfs rev. 23, so this PR updates our Parrot connector. I *think* this works for any libcvmfs version. I also made some changes on our end. I'd like to pass configuration to libcvmfs as directly as possible, so I marked some of the Parrot specific or legacy parts as deprecated. New users can use any desired options from the [libcvmfs docs](http://cvmfs.readthedocs.io/en/latest/cpt-configure.html). Aside from Parrot-internal options like repo switching, `--cvmfs-option` and `--cvmfs-option-file` should be preferred for configuring CVMFS in Parrot, since they use the same syntax as the FUSE module and libcvmfs.

Also, is there a reason Parrot explicitly disallows direct connections and requires a proxy?

### CODE REVIEW

**Comment by trshaffer** [comment]
See #1415

**Comment by dthain** [comment]
Parrot explicitly requires a proxy b/c the main repository operators are not set up to handle direct access traffic.  This protects against the situation where a relatively small number of direct clients could ruin performance for everyone by slamming the central repo.

**Comment by trshaffer** [comment]
OK, just checking if it's still needed. The proxy check happens on both old and new libcvmfs now.

Should there be a log warning if a user tries the new option args with old libcvmfs? Also, it seems like Parrot is running out of short argument letters

**Comment by dthain** [comment]
Well, as a general rule, combinations that don't work at all should result in an error.  Things that work but are not preferred should result in a warning.  So, if the new option format would not work at all with the old libcvmfs, that should be an error.

It's ok if the options are only in long format without a short letter.

**Comment by btovar** [comment]
Tim, is this ready to be merged?

**Comment by trshaffer** [comment]
I don't know of any outstanding issues, and it's been working well for my benchmarks here, but I'd still like to verify that nothing changed for the old library interface. If there's no hurry, I'd like to go over it again and test it next week when I'm back

**Comment by trshaffer** [comment]
All right @btovar, this seems to be behaving as expected under various libcvmfs/option combinations

**Pull request merged**
