### PR TITLE
set python path according to script

### PR DESCRIPTION
**Pull request by btovar**
Sets PYTHONPATH in cctools_python.

I am not too happy about setting PYTHONPATH implicitly for the user, as it may break local setups. That said, we cannot guarantee cctools_python to work correctly without this fix.

Let's give these solutions a try, but with our eyes open for something less icky.

(ref #847)

### CODE REVIEW

**Comment by batrick** [comment]
I need this patch to get `weaver -h` to work:

````
$ git diff
diff --git a/dttools/src/cctools_python b/dttools/src/cctools_python
index 7a7f730..e6f637d 100755
--- a/dttools/src/cctools_python
+++ b/dttools/src/cctools_python
@@ -42,8 +42,8 @@ match_versions () {
 find_python_path () {
        _script=$1
        _version=$2
-       _dirname="$(dirname $_script)/../../lib"
-       echo $_dirname/python$_version:$_dirname/python
+       _dirname="$(dirname $_script)/../lib/"
+       echo $_dirname/python$_version/site-packages/:$_dirname/python/site-packages/
 }
 
 if [ -z "$1" ]
````

**Comment by btovar** [comment]
Mmmm, it works for me. How are you calling it?

**Comment by btovar** [comment]
Oh, nevermind. I did not push my latest version. Sorry about that.

**Comment by btovar** [comment]
Fixed, thanks @batrick !

**Comment by batrick** [comment]
Works for me @btovar, if you are satisfied go ahead and merge it.

**Comment by dthain** [comment]
I can imagine many ways in which this could accidentally fail if the user ends up moving files here and there.  At a minimum, be sure to emit a detailed error message if the appropriate python lib directory is not found where it is expected..

**Pull request merged**
