### PR TITLE
Vine: add wrapper scripts to batch systems

### PR DESCRIPTION
**Pull request by tphung3**
Wrapper scripts are updated to use `vine_worker` and have names changed to avoid reusing WQ wrapper scripts. WQ's scripts should probably have their names changed too (e.g., from `condor_submit_workers` to `work_queue_condor_submit_workers`)

### CODE REVIEW

**Comment by tphung3** [comment]
Fix 2nd point in this issue https://github.com/cooperative-computing-lab/cctools/issues/3363

**Comment by btovar** [comment]
I'd recommend not renaming the wq scripts as several users know the current names.

**Comment by dthain** [comment]
Agreed that we should not rename the WQ scripts.  (That would also requiring changing all the documentation, examples, test scripts, etc)

Re the vine side of things, what would you think of consolidating all of the `vine_X_submit` scripts into one single `vine_submit_workers` script?

**Comment by dthain** [comment]
That's a good point.  In years past, I would have been reluctant to make this script depend upon Python.  But in a Conda world, I think it is the better way to go.

**Comment by dthain** [comment]
Oh, so my point was more about making one self-contained script, instead of having multiple scripts that invoke each other.

**Comment by dthain** [comment]
Suggestion on how to proceed in order to bring us up to date:
- Drop torque and pbs, since we have not used or tested those in quite some time.
- Keep condor, sge, and slurm, since that covers the hpc space pretty well today.
- Combine all the scripts into one file called `vine_submit_workers` including batch.submit.common.
- Keep your existing check of `-T type` as the first argument, and use that to call `condor_parse_args`, `sge_parse_args` and so forth...
-

**Comment by dthain** [comment]
That's looking nice, you are on the right track.

**Comment by tphung3** [comment]
If all is well this PR is ready to merge.

**Comment by dthain** [comment]
Script looks good, please update the corresponding documentation:
https://cctools.readthedocs.io/en/stable/taskvine/#running-a-taskvine-application

And add a manpage here:
https://github.com/cooperative-computing-lab/cctools/tree/master/doc/man/m4

**Comment by tphung3** [comment]
> Script looks good, please update the corresponding documentation: https://cctools.readthedocs.io/en/stable/taskvine/#running-a-taskvine-application
> 
> And add a manpage here: https://github.com/cooperative-computing-lab/cctools/tree/master/doc/man/m4

Doc changes in this PR https://github.com/cooperative-computing-lab/cctools/pull/3368

**Review by dthain — APPROVED** [review]

**Pull request merged**
