### PR TITLE
Work Queue Pool Timeout

### PR DESCRIPTION
**Pull request by NeilB879**
Made it so that when there are no masters in the work queue pool after a given amount of time work_queue will timeout.

### CODE REVIEW

**Comment by dthain** [comment]
Looks like the right idea.  Two minor changes:

- Call it "factory timeout" throughout; the name changed since this bug was filed.
- Add a brief item to the man page for the tool.

**Comment by dthain** [comment]
And what happens if the user doesn't set a factory timeout?

**Comment by NeilB879** [comment]
@dthain I have changed it to factory-timeout, updated the man page, and fixed the behavior if factory-timeout isn't set.

Is there anything else that needs to be added to this?

**Comment by dthain** [comment]
Neil, how did you go about testing this code?

**Comment by NeilB879** [comment]
I ran the command:

./work_queue_factory -M test --factory-timeout 5 -T condor
To test the timeout working properly when set. This displays an error message and then exits, however since in the mainloop there is a 30 second sleep period it will actually timeout in a much longer period  then intended (unless timeout is about 30 seconds), I am unsure if it changing this sleep timer based on the factory-timeout would be beneficial.

I also have used the makeflow command:
makeflow -M test -T wq ../test/syntax/collect.makeflow &

To generate a master (with the name test)

And then run with some variations with the first command to test that it properly, exits/runs when it should.

**Comment by dthain** [comment]
I don't think it's necessary to bring the resolution down below 30 seconds.
The main point is garbage collection, not precise timing.

**Comment by dthain** [comment]
@btovar merge when you are ready
fixes #984

**Comment by btovar** [comment]
On it.

**Comment by btovar** [comment]
@NeilB879: Note I made factory_timeout_start a local variable. 

Also, added factory-timeout as a field to the configuration file.

**Pull request merged**
