### PR TITLE
Http request format fix

### PR DESCRIPTION
**Pull request by hmeng-19**
change the `Request-URI` field of http requests:
 When there is no proxy to be used, the `Request-URI` field should be `abs_path`.

### CODE REVIEW

**Comment by hmeng-19** [comment]
This PR aims to fix #1287 .

**Comment by hmeng-19** [comment]
@dthain , please give it a look.

**Comment by hmeng-19** [comment]
@btovar , how do you think about this?

**Comment by hmeng-19** [comment]
It looks that autobuild can not send us email notification.
The record here http://ccl.cse.nd.edu/software/autobuild/ shows it should not have any bit damage to the code.

**Comment by btovar** [comment]
I asked suggest@cse about the emails. They have not responded yet. The error is:

   ----- Transcript of session follows -----
<btovar@nd.edu>... Deferred: alt4.aspmx.l.google.com.: No route to host
Warning: message still undelivered after 4 hours
Will keep trying until message is 5 days old

**Comment by btovar** [comment]
Rather than goto, you can use two scanf's in succession, or better yet, use the functions that Patrick added in pattern.h.

**Comment by hmeng-19** [comment]
@btovar , thanks for pointing out.
I double checked the code and noticed that `goto` is not really necessary here. So I just removed it.

Let me know whether this is ready to merge.

**Comment by btovar** [comment]
It looks good to me.

**Pull request merged**
