### PR TITLE
Vine declare file

### PR DESCRIPTION
**Pull request by btovar**
For #3146

Files are now registered with the manager with `vine_declare_*(m, ...)`. E.g.: `vine_declare_temp(m)`
The manager checks for duplicates, and only keeps one copy.

### CODE REVIEW

**Comment by dthain** [comment]
This is the right idea.  A few thoughts:

1 - We generally have `vine_manager_X` for internal operations on the `vine_manager` object, but `vine_X` for public API functions the the manager (`vine_submit`, `vine_hungry`, etc). While I see the rationale behind `vine_manager_file_X`, it's quite a mouthful for something we are going to say frequently.  I think a verb is needed.  Maybe `vine_declare_X` like you suggested before?

2 - No need to add an additional reference inside `vine_manager_declare_file`.  I think we only need to add refs when attaching a pointer to an object that we control.  (For example, we add a reference in `vine_task_add_{input/output}` because `vine_task_delete` -> `vine_mount_delete` -> `vine_file_delete`

3 - Once we have all the files entered into a file table, then the manager can delete the file table and all the files in it.  (So the user never has to delete files.)

**Comment by dthain** [comment]
Almost there, I think we want all the file creations to be manager methods and not object constructors, like this:
```
m = vine.Manager(9123);
f = m.declareFile(path);
f = m.declareURL(url);
```

And then the public file constructors go away, except for a and object that wraps a generic `vine_file`, something like this:

```
def declareFile( self, path ):
    return vine.File( vine_declare_file( self._manager, path ) )
```

Would that work?

**Comment by btovar** [comment]
Let me give it a go.

**Review by dthain — APPROVED** [review]

**Comment by btovar** [comment]
Ok, here we go....

**Pull request merged**
