### PR TITLE
Vine txn standard

### PR DESCRIPTION
**Pull request by btovar**

### CODE REVIEW

**Comment by dthain** [comment]
It's ok to change the log format, but then we also need to change the consumers of that log in the same PR.
@BarrySlyDelgado @colinthomas-z80 does this affect your viz tools?

**Comment by btovar** [comment]
Yes, I decided to change this before we build more tools on the log.
I'll submit a pr for Barry's tools.

**Comment by dthain** [comment]
Something that Colin and I discussed (and I think this change reflects) is that a TRANSFER event should only be used for a substantial data movement between the manager and worker, and not just for metadata describing some other kind of transfer.

**Comment by btovar** [comment]
Yes, I agree! Let me look for those.

**Comment by colinthomas-z80** [comment]
Feel free to change. I need to rework my graphing tools anyway

**Comment by BarrySlyDelgado** [comment]
Should the worker_id be used in WAITING_RETRIEVAL/DONE/RETRIEVED lines too? The transfer change helps as I originally had to loop through the tr log twice once tasks were already mapped to workers. The changes to the tool should be minor.

**Comment by btovar** [comment]
Barry, yes, I have commits for that too. I saw that in your script, which made obvious that using worker-address was a mistake.

**Review by BarrySlyDelgado — APPROVED** [review]

**Review by colinthomas-z80 — APPROVED** [review]

**Pull request merged**
