### PR TITLE
make_cache_name called one time per file/directory

### PR DESCRIPTION
**Pull request by btovar**
@dthain @nhazekam

### CODE REVIEW

**Comment by dthain** [comment]
Looks like you are changing it from a stateless function to one that adds state to the file object.
In that case, be sure to make the function idempotent by checking to see if it has already been generated, and then to free the state when the file object goes away.

**Comment by btovar** [comment]
make_cache_name is now only called inside work_queue_file_create.

**Comment by dthain** [comment]
Unless I am missing something, cached_name isn't freed.
I think it should be cleaned up in work_queue_task_delete

**Comment by btovar** [comment]
Correct, I'll fix it.

**Comment by dthain** [comment]
Or, to make things even clearer, there should be a work_queue_task_file_delete to mirror w_q_t_f_create

**Comment by btovar** [comment]
Testing still, do not merge.

**Comment by btovar** [comment]
Done. Added wq_file_delete too.

**Pull request merged**
