### PR TITLE
work_queue_worker export resources

### PR DESCRIPTION
**Pull request by btovar**
Request by @khurtado, for better reporting to the CMS dashboard.

### CODE REVIEW

**Comment by dthain** [comment]
Maybe I am reading this incorrectly, but it doesn't seem right to me.

It looks like the intent of the code is to pass to the worker the env vars representing the total amount of  resources managed by the worker (manual_{cores|disk|memory}.

I think what we want is to pass to the worker env vars representing the resources allocated to that particular *task*, e.g. `CORES=task->resources->cores`.

**Comment by btovar** [comment]
You are right, but actually I think we want both. Let me think more about it.

@khurtado wants to know the size of the worker, but maybe they really want to know the size of the task.

**Comment by annawoodard** [comment]
I think what we need is the size of the task. This is for reporting to dashboard, and each task will be doing its own reporting.

**Comment by btovar** [comment]
Great, disregard this commit then.

**Comment by khurtado** [comment]
I agree with @annawoodard, sorry if there was any misunderstanding!

**Comment by btovar** [comment]
@dthain, added changes we talked about this morning.

**Comment by dthain** [comment]
496dc95 appears to be setting the environment at the master side, which isn't quite right.

I think we want the *worker* to set `CORES, MEMORY, DISK` at the moment of execution,
since they describe the size of the resource container in which the task is run.

This is because the task may not specify some resource, or it may specify a range, or something more complex.  The actual allocation is made by the worker and is distinct from the request, so the worker should specify the info.

If that's not clear, let's talk in person.

**Comment by btovar** [comment]
Not quite. We are adding the variables to the environment of the task. They do not get set until work_queue_process does its thing.

**Comment by btovar** [comment]
Oh, I see what you mean now.

**Comment by btovar** [comment]
@dthain ready to merge if you are.

**Comment by dthain** [comment]
Looks good!

**Pull request merged**
