### PR TITLE
Don't count status connections as workers

### PR DESCRIPTION
**Pull request by btovar**
Fix for #2195

### CODE REVIEW

**Comment by zhxu73** [comment]
I don't think it fixes the my problem, it still spawns 1 less worker.
The position I traced to is in `work_queue_factory.c`

work_queue_facotry.c, mainloop(), line ~832
a masters_list is created by do_direct_query()
```c
if(using_catalog) {
	masters_list = work_queue_catalog_query(catalog_host,-1,project_regex);
}
else {
	masters_list = do_direct_query(master_host,master_port);
}
```
work_queue_factory.c, do_direct_query(), line ~228
Creation process of the masters_list has something to do with the short "status" link that it connect to my WQ master.
```c
struct jx *jarray = jx_parse_link(l,stoptime);
```
line ~236
```c
struct jx *j = jarray->u.items->value;
j->type = JX_OBJECT;
	
struct list* master_list = list_create();
list_push_head(master_list, j);
```

work_queue_facotry.c, mainloop(), line ~856
The masters_list is then pass to count_workers_connected(), in which it returns 1 if my WQ master is running prior to the factory, and 0 otherwise (no other workers are running external to this).
So I persume that do_direct_query() definitely "record" the link to my WQ master, and count_workers_connected() mistakenly count that as a worker.
```c
int workers_connected = count_workers_connected(masters_list);
```

work_queue_facotry.c, mainloop() line ~892
since `workers_connected` is 1, thus cause workers_waiting_to_connect to be -1, which cause the factory to think there are some external worker.
```c
// if negative, this means workers external from this factory have
// connected.
int workers_waiting_to_connect = workers_submitted - workers_connected;

if(workers_waiting_to_connect < 0) {
	debug(D_WQ,"%d workers already connected from other sources", -workers_waiting_to_connect);
}
```

The -1 also reflect in the `-dall` logs as well
```bash
2019/10/31 14:50:19.55 work_queue_factory[9876] wq: applying minimum of 1 workers
2019/10/31 14:50:19.55 work_queue_factory[9876] wq: 1 workers already connected from other sources
```

**Comment by zhxu73** [comment]
Ah, never mind, sorry, My recompiled WQ master isn't in the PATH, the old one is

**Comment by zhxu73** [comment]
But I am still curious why is it a problem at `work_queue.c` rather than in `work_queue_factory.c`?
Is it because the status link actually exchange some info about both side, so that they what type of node the other one is?

**Comment by btovar** [comment]
@zhxu73 When the factory decides how many workers to run, it takes into account the workers count at the master. The master was counting the connection of the factory itself as a worker connection.

This is why the problem was only observed when the factory directly asked the master, and not when the factory got its information from the catalog.

**Pull request merged**
