### PR TITLE
Vine: make sure file is fsync'ed at worker

### LINKED ISSUE #3448: Vine: vine_transfer needs fsync to work properly
Whenever a file is transferred between workers, the receiving worker must call `fsync` on the file descriptor to ensure that the file is dumped to disk.

Evidence: running a workflow with 1024 tasks, each with a poncho environment tarball ~1GB:
- no `fsync`: `success: 78, failure: 946`
- `fsync`: `success: 1024, failure: 0`.

### PR DESCRIPTION
**Pull request by tphung3**
This PR fixes #3448 and #3446.

### CODE REVIEW

**Comment by dthain** [comment]
Still have to close the file on the way out!

**Comment by tphung3** [comment]
This PR is RTM.

**Comment by btovar** [comment]
Shouldn't the fsync come after the fclose?

Just a shot in the dark here, but are we sure is really the fsync that's working, or is fsync causing a delay for long enough that some race condition is minimized?  If the workers are not running on top of a shared filesystem, this fsync is highly suspicious.

**Comment by dthain** [comment]
The fsync operates on an open fd, so it's in the right place.

But I agree that this behavior doesn't yet make sense.  I like the race condition hypothesis!

**Comment by btovar** [comment]
Oh right, needs the open fd.

**Pull request merged**
