### PR TITLE
Reproducibility edits to BGD example

### PR DESCRIPTION
**Pull request by David-Simonetti-ND**
Changed around some resource allocations in the example and allowed the number of tasks to be passed as an argument on the command line.

### CODE REVIEW

**Comment by dthain** [comment]
Hold on - I want to make sure that we get the right things into the right places here.

The `examples` directory is meant to be ...  examples of how to use TaskVine, and may change as we add features, find better ways to express things, etc.  It's fine that you are adding command-line switches and so forth.  But surely cores(0) and disk(0) isn't the final form of what we want the examples to look like.

However, to the extent that our goal is to capture the figures in the paper, just put the exact code of `vine_example_gradient_descent.py` that you used into the taskvine-paper repository.  So then that repository is a faithful representation of what's in the paper, warts and all.  And the software repository can evolve as needed.

**Comment by David-Simonetti-ND** [comment]
I see, things make a lot more sense now

**Comment by btovar** [comment]
Including the python examples makes sense, but not so much for the modified C examples. I was trying to avoid the need of any compilation and for the compiled examples to be included in the conda distribution. The reasoning was that compilation is harder to get right for every case and we do not want the reviewers to need to modify a makefile.

Were any of the figures produced from the C examples?

**Comment by dthain** [comment]
I'm pretty sure the figures were all done with python.

**Comment by David-Simonetti-ND** [comment]
@btovar This is a small change that just adds an extra option to the bgd example for number of tasks. Should be safe to merge.

**Comment by btovar** [comment]
Is it different from the one already in taskvine-paper?

**Pull request merged**
