### PR TITLE
Create UUID for Chirp server to send to Catalog.

### PR DESCRIPTION
**Pull request by batrick**
This is a prereq for #1324, #1325, and #1326.

### CODE REVIEW

**Comment by batrick** [comment]
Apparently there is a standard API via uuid.h in darwin/linux. I will see if that's usable instead of what I wrote in dttools.

**Comment by batrick** [comment]
I elected to use the simple uuid implementation I wrote. I think this is ready for merging.

**Comment by dthain** [comment]
It's fine (even preferable) to have our own uuid implementation, but I would like to avoid relying on unusual gcc path options.  If necessary, please call it "cctools_uuid.h" or something like that.

**Comment by dthain** [comment]
While I understand that, technically, `_t` is a reserved suffix, that's the customary usage in most C code, including ours.  `uuid_t` or `cctools_uuid_t` would be preferable to `uuid`.

(This will be a very handy feature for tracking and reporting.)

**Comment by batrick** [comment]
`uuid_t` is off the table because Darwin includes its own `uuid.h` in some of its system headers so the conflict cannot be avoided.

I will make the other changes you've suggested.

**Comment by batrick** [comment]
@dthain please merge if you think this is ready.

**Pull request merged**
