### PR TITLE
wait for makeflow jobs even when remote submission fails.

### PR DESCRIPTION
**Pull request by btovar**
The use case is amazon batch jobs where we could not create new
submissions because some hard limit.

Solves #2161

### CODE REVIEW

**Comment by btovar** [comment]
Got it.

Should we still try to submit local jobs? If makeflow_dispatch_ready_jobs breaks, then they won't run even if they could.  With the current pr they would get run after all the timeouts, which is also not desirable.

**Comment by dthain** [comment]
Ah, good point!
Any suggestions on how to handle this cleanly?

**Comment by btovar** [comment]
@dthain: cc8e7480496d63ab02701186542b522e4e23b3c4 makes it so that local jobs are still submitted even if the batch system times out.

**Comment by epyifany** [comment]
@btovar I have just ran tested a makeflow example and the timeouts have helped. Jobs are successfully submitted. Thanks!

**Pull request merged**
