### PR TITLE
Read the docs

### LINKED ISSUE #2118: Convert Documentation to readthedocs.io
- Explore technology/language choices at readthedocs.
- Convert existing manuals/pages to new format (try to automate as much as possible.)
- Update `make docs` to build pages automatically.
- Connect cctools repo to readthedocs to deploy docs automatically as needed.

### PR DESCRIPTION
**Pull request by btovar**
WIP: Fixes #2118

Current progress:   https://cctools.readthedocs.io/en/latest/

### CODE REVIEW

**Comment by dthain** [comment]
This is looking great!
What would it take to get more granular sections/subsections in the left-hand panel?

**Comment by btovar** [comment]
I'm looking into it... I can do it manually in the mkdocs conf file, but there must be a switch that makes it automatically.

**Comment by dthain** [comment]
I'm taking a crack at the merge on this one.
Also looking at conversion from m4 to md for man pages.

**Comment by dthain** [comment]
Oh good grief:
https://stackoverflow.com/questions/29522699/gnu-m4-escaping-backticks

**Comment by dthain** [comment]
Superseded by #2160

**Pull request closed without merging**
