### PR TITLE
Golang api for Work Queue and Chirp

### PR DESCRIPTION
**Pull request by charleszheng44**
Add golang support for Work Queue and Chirp

### CODE REVIEW

**Comment by charleszheng44** [comment]
@btovar @dthain Do you think this PR can be merged?

**Comment by btovar** [comment]
Charles, please do a rebase to the current master head to get rid of all of the merge commits.

**Comment by charleszheng44** [comment]
@btovar the merge commits are from a closed PR that refers to this one. This PR has already rebase the latest master head.

**Comment by btovar** [comment]
It looks like this PR has the closed PR in its history.  This means that it has not been rebased to the current master head.

**Pull request closed without merging**
