### PR TITLE
Work Queue Container Support

### PR DESCRIPTION
**Pull request by charleszheng44**
add --run-in-docker option for work_queue_worker, it enable to run work_queue_worker process inside a docker container

### CODE REVIEW

**Comment by dthain** [comment]
@charleszheng44 let's get this cleaned up now so that other people can use it.

Please take a pass through and remove al lthe extraneous comments and printfs.

Also, I see that work_queue_process_execute and work_queue_process_execute_container share a lot of similar code.  Find a way to avoid that duplication.

**Comment by charleszheng44** [comment]
@dthain  Several arguments, like container_mode and image_name need to be passed into the 
work_queue_process_execute_container function. 

What about a generic function work_queue_process_execute(struct work_queue_process *p, ...) using argument list?

**Comment by dthain** [comment]
Right, pass those things as args and leave them null if irrelevant to the container mode.

**Comment by dthain** [comment]
This pull request seems to be mixing two features.
Best thing to do is restart from a clean branch, apply code changes and make pull request.

**Comment by btovar** [comment]
Closing, given last comment.

**Pull request closed without merging**
