### PR TITLE
To add a SGE compatibility code line

### PR DESCRIPTION
**Pull request by isanwong**
add #$ -S /bin/bash to sge.wrapper file

### CODE REVIEW

**Comment by batrick** [comment]
@isanwong, what is the reason SGE needs to run the wrapper in bash?

**Comment by isanwong** [comment]
I just can't commit a makeflow file successfully without this line in the generated sge.wrapper file.

**Comment by isanwong** [comment]
Sounds that the Makeflow program can't detect if the jobs submitted first returned, and just waitting forever...

**Comment by btovar** [comment]
@isanwong, could you tell us if:

#! /bin/sh
#$ -S /bin/sh

works for you? (Note that we simply add a line below the first line, we do not modify the first line).

**Comment by isanwong** [comment]
Yes. It works for me.

2015年8月19日星期三，Benjamin Tovar <notifications@github.com> 写道：

**Comment by btovar** [comment]
Excellent, we'll make a patch for that. Thanks again for your report!

**Comment by isanwong** [comment]
You're welcome.

2015年8月19日星期三，Benjamin Tovar <notifications@github.com> 写道：

**Comment by batrick** [comment]
Ben, I suggest we let him update his PR if he wants so he gets credit. It
encourages him to contribute in the future.

On Wed, Aug 19, 2015 at 11:06 AM, Benjamin Tovar <notifications@github.com>
wrote:

> Excellent, we'll make a patch for that. Thanks again for your report!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cooperative-computing-lab/cctools/pull/896#issuecomment-132632932>
> .
>



-- 
Patrick Donnelly
Department of Computer Science and Engineering
University of Notre Dame

**Comment by batrick** [comment]
Thanks @isanwong!

**Pull request merged**
