### PR TITLE
Flatten resource monitor output in Condor

### PR DESCRIPTION
**Pull request by nhazekam**
@btovar This is attempt 2 take a look and let me know what you think. #1364

### CODE REVIEW

**Comment by btovar** [comment]
Nick, works for me, but it seems there are some conflicts with the current master.

**Comment by nhazekam** [comment]
Thanks for pointing that out, had not noticed.

**Comment by nhazekam** [comment]
Before we merge this, because the directory, if one is used, is created by the monitor wrapper should I delete this in clean? It is not currently logged or tracked.

**Comment by btovar** [comment]
If we create the directory (was not there before) and if after -c the directory is empty, then yes, we should remove it.

**Comment by nhazekam** [comment]
I'll work on adding that handling.

**Comment by btovar** [comment]
Nick is this ready to be merged? Did you test it?

**Comment by nhazekam** [comment]
Yes, just for documentation, if the directory doesn't exist Makeflow will make it, if Makeflow created it Makeflow will delete it.

**Comment by btovar** [comment]
Great, thanks Nick

**Pull request merged**
