### PR TITLE
 Amazon Batch module for makeflow

### PR DESCRIPTION
**Pull request by btovar**
Stashed version of cf4f917865213cf344f3e60107510744407e3ea1^..cd7452094f538756a3f99fd3b79eb1603c4f3bc3

Supersedes #1673

### CODE REVIEW

**Comment by btovar** [comment]
@Nekel-Seyew: please verify it still works as intended.

**Comment by Nekel-Seyew** [comment]
Tested it, so far seems to be working. Will let my bwa-gatks run finish, and when it does, get back to you. But it probably will work!

**Comment by Nekel-Seyew** [comment]
turns out the aws cp command isn't being used with the recursive command, which is causing our lifemapper stuff to fail

going to update my repo to include that

**Comment by dthain** [comment]
Is this superseded by #1905?

**Comment by Nekel-Seyew** [comment]
Yes, I took the changes Ben did here and added them to my own changes in #1905

**Pull request closed without merging**
