### PR TITLE
Lint settings

### PR DESCRIPTION
**Pull request by Jbrocket**
## Proposed changes
Make lint now goes into poncho, resource_monitor, and dttools as well. And probably more packages to come as well.

## Post-change actions

Put an 'x' in the boxes that describe post-change actions that you have done.
The more 'x' ticked, the faster your changes are accepted by maintainers.

- [x] `make test`       Run local tests prior to pushing.
- [x] `make format`     Format source code to comply with lint policies. Note that some lint errors can only be resolved manually (e.g., Python)
- [x] `make lint`       Run lint on source code prior to pushing.
- [x] Manual Update     Did you update the manual to reflect your changes, if appropriate? This action should be done after your changes are approved but not merged.
- [x] Type Labels       Select github labels for the type of this change: bug, enhancement, etc.
- [x] Product Labels    Select github labels for the product affected: TaskVine, Makeflow, etc.
- [x] PR RTM            Mark your PR as ready to merge.

## Additional comments
Are there any auto-formatters for flake8/python

### CODE REVIEW

**Comment by tphung3** [comment]
@Jbrocket You can add these errors to the ignore list: E306, E226, E231, E241, E126, E123 (mostly formatting errors).
Note that for `./poncho/library_network_code.py:77:21: F821 undefined name 'name'` and ` ./poncho/wq_network_code.py:47:25: F821 undefined name 'name'`, please put a custom ignore-to-lint message as this undefined name is expected (the name() function will be filled in a later time when code is executed). I think `flake8` supports an inline ignore directive as a Python comment.
Other errors should be fixed as appropriate.

**Comment by tphung3** [comment]
The history is too cluttered as @Jbrocket mentioned. Please clean it by reset --hard to [cbf3b06](https://github.com/cooperative-computing-lab/cctools/pull/3518/commits/cbf3b0650f2d4826232bf3590a009d46550cd2b6), merge master, then apply [e124390](https://github.com/cooperative-computing-lab/cctools/pull/3518/commits/e124390fcfd3b6523a40367ed6db0bccd7531bb3) and any other new commits. Remember to note down important commits so you don't lose them or create another local branch and upstream it to this PR.

**Comment by dthain** [comment]
RTM?

**Review by tphung3 — APPROVED** [review]
Looks good!

**Review by dthain — APPROVED** [review]

**Pull request merged**
