### PR TITLE
Initial fix for #1836

### LINKED ISSUE #1836: Parrot issues reading some symlinks from oasis.opensciencegrid.org
Hello,
I'm trying to use  voms  from `oasis.opensciencegrid.org` via parrot and noticed there are some symbolic link files that just couldn't be read (the file the links are pointing to can be accessed though).

For example, from a machine with cvmfs, I can get:

```
$ ls -l /cvmfs/oasis.opensciencegrid.org/mis/osg-wn-client/3.3/3.3.31/el6-x86_64/etc/grid-security/certificates/70d35895.0
lrwxrwxrwx 1 cvmfs cvmfs 15 Jan 14 21:14 /cvmfs/oasis.opensciencegrid.org/mis/osg-wn-client/3.3/3.3.31/el6-x86_64/etc/grid-security/certificates/70d35895.0 -> cilogon-osg.pem
```

and this is what I get with parrot:

```
-bash-4.2$ ./parrot_run bash
bash-4.2$ ls -l /cvmfs/oasis.opensciencegrid.org/mis/osg-wn-client/3.3/3.3.31/el6-x86_64/etc/grid-security/certificates/70d35895.0
LibCvmfs version 2.4, revision 25
ls: cannot read symbolic link /cvmfs/oasis.opensciencegrid.org/mis/osg-wn-client/3.3/3.3.31/el6-x86_64/etc/grid-security/certificates/70d35895.0: No such file or directory
lrwxrwxrwx 1 root root 15 Jan 14 22:14 /cvmfs/oasis.opensciencegrid.org/mis/osg-wn-client/3.3/3.3.31/el6-x86_64/etc/grid-security/certificates/70d35895.0
bash-4.2$ ls -l /cvmfs/oasis.opensciencegrid.org/mis/osg-wn-client/3.3/3.3.31/el6-x86_64/etc/grid-security/certificates/cilogon-osg.pem
-rw-r--r-- 1 root root 1383 Jan 14 22:14 /cvmfs/oasis.opensciencegrid.org/mis/osg-wn-client/3.3/3.3.31/el6-x86_64/etc/grid-security/certificates/cilogon-osg.pem
bash-4.2$ 
```

Any hint on how to solve this?

### PR DESCRIPTION
**Pull request by trshaffer**
Do not merge before checking with @btovar

Fixes #1836

### CODE REVIEW

**Comment by btovar** [comment]
Tim,
The following non-existing path segfaults with your fix:

./parrot_run stat /cvmfs/oasis.opensciencegrid.org/mis/osg-wn-client/3.3/3.3.31/el6-x86_64/etc/grid-security/certificates/70d35895.0.nonsense

Before your fix, I get the correct 'No such file or directory'

**Comment by btovar** [comment]
Tim:

parrot/src/parrot_run stat /cvmfs/oasis.opensciencegrid.org/mis/osg-wn-client/3.3/3.3.31/el6-x86_64/usr/share/man/overrides

segfaults.

**Comment by dthain** [comment]
Is this PR needed or is it superseded by #1851?

**Comment by trshaffer** [comment]
Not superseded, but I wanted to be cautious with this PR as it touches Parrot's symlink handling under CVMFS. If @khurtado has been using this branch for a bit without issue, it should be merged into `master`

**Comment by khurtado** [comment]
It fixed the issues I had at least. I have another bug in #1855 after this fix, but I don't know if they are correlated.

**Comment by trshaffer** [comment]
Merging, as this is not related to #1855

**Pull request merged**
