### PR TITLE
Readthedocs Take 2

### PR DESCRIPTION
**Pull request by dthain**
Extending @btovar PR #2130 by merging latest doc changes.
First pass at code to transform M4 man pages into Markdown.
Still working on it...

### CODE REVIEW

**Comment by dthain** [comment]
@btovar please deploy the latest docs to readthedocs.io.   It's not perfect yet, but it's coming along.

**Comment by btovar** [comment]
Still one more step to do that. readthedocs expects all the pages to be already present, but we are generating the manuals via make. I'm investigating how we can do that step.

**Comment by dthain** [comment]
I have no objection if you just add the generated MD man pages into the repository.
As long as we (for now) retain the capability to re-create them.

**Comment by btovar** [comment]
I did not see  help.md, or help/index.md.  Did you forget to include it in the commit?

**Comment by dthain** [comment]
I must have, let's see...

**Comment by dthain** [comment]
Just added it via direct push to master.

**Pull request merged**
