### PR TITLE
Vine: tool for worker performance

### PR DESCRIPTION
**Pull request by JinZhou5042**
## Proposed changes

This script processes a performance file and generates corresponding output showing the busy and idle times of workers while running this application. The output will be saved in the same folder as the input performance log file.

worker_performance

The left figure shows how the number of busy and idle workers change as time elapsing, the right one shows how they change as tasks are completed.

## Post-change actions

Put an 'x' in the boxes that describe post-change actions that you have done.
The more 'x' ticked, the faster your changes are accepted by maintainers.

- [ ] `make test`       Run local tests prior to pushing.
- [ ] `make format`     Format source code to comply with lint policies. Note that some lint errors can only be resolved manually (e.g., Python)
- [ ] `make lint`       Run lint on source code prior to pushing.
- [ ] Manual Update     Did you update the manual to reflect your changes, if appropriate? This action should be done after your changes are approved but not merged.
- [ ] Type Labels       Select github labels for the type of this change: bug, enhancement, etc.
- [ ] Product Labels    Select github labels for the product affected: TaskVine, Makeflow, etc.
- [ ] PR RTM            Mark your PR as ready to merge.

## Additional comments
This section is dedicated to changes that are ambitious or complex and require substantial discussions. Feel free to start the ball rolling.

### CODE REVIEW

**Comment by dthain** [comment]
How is this different from the "workers" plot produced by `vine_graph_log` ?

**Comment by JinZhou5042** [comment]
> How is this different from the "workers" plot produced by `vine_graph_log` ?

I think this tool demonstrates the worker performance in a finer granularity, we can see the portion of busy or idle workers in a specific running time, or in the process of completing tasks.

This could be helpful while overseeing the connection or disconnection situation of workers while running tasks, but I don't have a compelling reason that it should be integrated into our repo. How do you think?

**Comment by dthain** [comment]
So, the principle here is that `vine_graph_log` is the tool for displaying the contents of the performance log.  If it needs an additional kind of output, then please augment that tool to produce this graph.

**Comment by JinZhou5042** [comment]
> So, the principle here is that `vine_graph_log` is the tool for displaying the contents of the performance log. If it needs an additional kind of output, then please augment that tool to produce this graph.

Sure, got that idea!

**Pull request closed without merging**
