### PR TITLE
add explicit port to master node

### PR DESCRIPTION
**Pull request by btovar**
@batrick, does this look correct? This is in case the default port is already taken.

With this modifications, I am getting the following error:

2015/06/29 09:09:27.42 makeflow[2714] batch: exited abnormally: ERRORED (Invalid cross-device link)

### CODE REVIEW

**Comment by batrick** [comment]
@btovar I'm looking into this.

**Comment by btovar** [comment]
If it makes any difference, both confuga root and makeflow workdir are on AFS, but different cells

**Comment by batrick** [comment]
@btovar I think the problem is that you didn't modify makeflow as well:

    makeflow --batch-type=chirp --working-dir=chirp://localhost/ makeflow/example/example.makeflow

You need to do:

    makeflow --batch-type=chirp --working-dir=chirp://localhost:9000/ makeflow/example/example.makeflow

As for the error message you found, you can't run Chirp jobs which use LINK bindings (the default) because AFS doesn't let you do cross-directory hard links.

**Comment by btovar** [comment]
Thanks Patrick, I did use localhost:9000. Could you add a comment regarding AFS in "Getting Started with Confuga"?

**Comment by batrick** [comment]
I think I'll add a warning in Chirp as well, like we do for batch job Condor.

**Comment by btovar** [comment]
I can confirm that on /tmp the example works.

**Comment by batrick** [comment]
@btovar please go ahead and merge this after fixing the makeflow line and updating the man page example too.

**Pull request merged**
