### PR TITLE
disk loop allocation cleanup

### PR DESCRIPTION
**Pull request by btovar**
@nkremerh please review (and test).

### CODE REVIEW

**Comment by nkremerh** [comment]
I believe we chose to stick with the "disk allocation" terminology over "loop device" due to semantics (see #1238) because we may use methods of _disk allocation_ other than loop devices in the future. What do you think?

**Comment by btovar** [comment]
Uhm, forgot about that.

**Comment by btovar** [comment]
what about know?

**Comment by nkremerh** [comment]
Looks great! Tested for functionality, looks good to me.

**Pull request merged**
