### PR TITLE
do not set HTTP_PROXY if using -p, instead set PARROT_HTTP_PROXY

### PR DESCRIPTION
**Pull request by btovar**
With regards to #1850

### CODE REVIEW

**Comment by dthain** [comment]
Careful, CVMFS tests are failing on this PR

**Comment by btovar** [comment]
I was afraid of that. It was likely some other code assumed HTTP_PROXY was set.

**Comment by btovar** [comment]
Actually only in rh5. I wonder if it is a transient.

**Comment by btovar** [comment]
I think I know. Since we did not use rh5 in autobuild for a long time, the libcvmfs used there is a little behind and different from the other platforms.

**Comment by btovar** [comment]
Now rh5 passes the cvmfs tests.

**Pull request merged**
