### PR TITLE
Added function to escape Condor, called in batch_job_condor

### PR DESCRIPTION
**Pull request by nhazekam**
Added function that escapes quotes which is required in a condor submit file. Needed as quotes are used in wrapping of commands with wrappers and resource monitor.

### CODE REVIEW

**Comment by nhazekam** [comment]
Resolves #1348 @btovar test when able.

**Comment by dthain** [comment]
Please add a test case.

**Comment by nhazekam** [comment]
On it.

**Comment by btovar** [comment]
It does not quite work for me.

Add the following to example.makeflow, just before the first rule:

export MAGICK_THREAD_LIMIT=4

MEMORY=512
DISK=100
CORES=4

and run with:  makeflow -Tcondor example.makeflow  --monitor=mon -dall

(you need to that from /tmp)

You'll see only one rule completes.

**Comment by btovar** [comment]
This is what condor ends up seeing:

Arguments = ".//resource_monitor --no-pprint --with-output-files=mon/resource-rule-1 -L ''''cores:' '4'''' -L ''''memory:' '512'''' -L ''''disk:' '100'''' -V ''''category:default'''' --sh \"/usr/bin/convert -swirl 90 capitol.jpg capitol.90.jpg\""

It does not look quite right.

**Comment by nhazekam** [comment]
I am taking a look right now. I'll see what change I made that caused this.

**Comment by nhazekam** [comment]
I was able to get it to run:

".//resource_monitor --no-pprint --with-output-files=./resource-rule-0 -L '''cores: 2''' -L '''memory: 10''' -L '''disk: 20''' -V '''category:merge''' --sh ""/usr/bin/convert -delay 10 -loop 0 capitol.jpg capitol.90.jpg capitol.180.jpg capitol.270.jpg capitol.360.jpg capitol.270.jpg capitol.180.jpg capitol.90.jpg capitol.montage.gif"" "

Unfortunately, when you have a directory for monitor, such as with the above example, it fails to find the file. looking into that now.

**Comment by btovar** [comment]
Nick, see: #1364

**Comment by dthain** [comment]
If inducing the desired behavior from Condor is too complicated, perhaps we might consider changing the behavior of MF/RM to live within the constraints.

(For example, we might consider having Makeflow consolidate all the resource records into a single output file.  We don't have to do that, just pointing it out as an option.)

**Comment by btovar** [comment]
Nick, should we merge this one?

**Comment by nhazekam** [comment]
Were you able to successfully run resource monitor through condor? If so I
think it's good to go and doesn't effect any other systems.
On Jun 2, 2016 12:14 PM, "Benjamin Tovar" <notifications@github.com> wrote:

Nick, should we merge this one?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/cooperative-computing-lab/cctools/pull/1362#issuecomment-223342033>,
or mute the thread
<https://github.com/notifications/unsubscribe/AE_SNyLOCWRq5kFl922C1anJi9I-iAyUks5qHwFXgaJpZM4IrrA_>
.

**Comment by btovar** [comment]
It does  if I do: makeflow --monitor=.

**Comment by nhazekam** [comment]
To reiterate: the remaining issue at this point for resource monitor in Condor is directories. Pointing to that issue #1364

**Pull request merged**
