### PR TITLE
adds unponcho mini task

### PR DESCRIPTION
**Pull request by BarrySlyDelgado**
added the function for a poncho unpack mini task

### CODE REVIEW

**Review by dthain — CHANGES_REQUESTED** [review]
Please make sure that you do a minimal build and test before pushing, I see at least one obvious typo that would prevent a good build.

Also, please add the corresponding bits to the Python interface in taskvine.binding.py.

**Comment by BarrySlyDelgado** [comment]
The minitask and tasks from `vine_example_unponcho.c` complete successfully however, it seems that tasks are not reusing the unpacked package from the minitask this is evident from the absence of `logmsg directory ${UNPACK_TO} is not empty. Not expanding environment file again` in the output. Investigating this now.

**Comment by BarrySlyDelgado** [comment]
Initially thought it wasn't working as intended but after a lot of gdb I realized it was actually working. The issue was that I didn't realize that doing `pp_run -e <directory>` doesn't produce the log message i thought it did but rather `pp_run -u <directory> -e <env>` does. Added an example with and without unponcho which is nicely just a change in 2 lines. working on python interface and this should be wrapped up.

**Comment by BarrySlyDelgado** [comment]
@dthain This should be ready now.

**Review by dthain — APPROVED** [review]

**Comment by dthain** [comment]
LGTM

**Pull request merged**
