### PR TITLE
Prune

### PR DESCRIPTION
**Pull request by pivie**
This branch has at least some of the whitespace fixed.

### CODE REVIEW

**Comment by batrick** [comment]
In the future, please just force push to the branch on the original pull request. There's no need to open a new one.

**Comment by pivie** [comment]
I am trying to get in the habit of doing things in a branch. I forgot to do that with the other pull request, so I wanted to fix it. I hope that is okay. If you want me to go back to the other one, I will.

I prefer to have a little extra space at the end of a file, but I guess that comes from using a GUI editor. I will try to get over it. Is the current PR okay?

**Comment by batrick** [comment]
Commit looks good to me now. I haven't looked at the changes.

**Comment by dthain** [comment]
Peter is this ready to merge?

**Comment by pivie** [comment]
Yes

**Comment by pivie** [comment]
Wait, not this one, #1338 is the right one. Closing this one out.

**Pull request closed without merging**
