### PR TITLE
Added Blue Waters support

### PR DESCRIPTION
**Pull request by nhazekam**
Incorporates Blue Waters into current version. @btovar @dthain

### CODE REVIEW

**Comment by btovar** [comment]
Is this ready to be merged? If so, I can also add it to the release.

**Comment by dthain** [comment]
Please add to the man page and makeflow manual.

**Comment by dthain** [comment]
That is, @nhazekam should add to the man page and manual.

**Comment by nhazekam** [comment]
Will do.

**Comment by nhazekam** [comment]
@btovar Should be good to go.

**Pull request merged**
