### PR TITLE
Updated makeflow tests to use INPUTS/OUTPUTS

### PR DESCRIPTION
**Pull request by nhazekam**
Fixes failure in Makeflow GC on-demand test and adds INTPUTS and OUTPUTS line to test makeflows so as to eliminate the notice lines printed during testing.

### CODE REVIEW

**Comment by nhazekam** [comment]
Addresses issue #1007. @btovar @dthain

**Comment by btovar** [comment]
Looks good.

**Comment by dthain** [comment]
Ok here

**Comment by dthain** [comment]
Make sure to close bug #1007 as well

**Pull request merged**
