### PR TITLE
Batch job option fix

### PR DESCRIPTION
**Pull request by nhazekam**
This waits to free until after we have made a duplicate of the new value. This prevents an issue if the old value passed back in. e.g. as in Makeflow

previous = batch_queue_get_option (q, "batch-options");
if(new-options)
    batch_queue_set_option(q, "batch-options", new-options);

run task

if(previous)
    batch_queue_set_option(q, "batch-options", previous);

Set option duplicates the passed value, and removes the previous value. When removing the previous value, it also frees that value as batch_job created it in the first place. The issue occurs when you pass back in the original value that you retrieved and it has already been freed. This happens regardless of whether you set new options or not. 

This pull request still frees the internal copy when a new value is set. It also returns a copy on get so we don't have issues if a new value is set while a pointer is held.

Instead of the solution here we could respect const char and not strdup the value, relieving the need to free at all in batch options. 

Before this is merged I need to go through and make sure memory leaks weren't added by strdup on get_option and feature.

Definitely open to a better solution, but this works in SLURM. @btovar @dthain

### CODE REVIEW

**Comment by nhazekam** [comment]
@btovar How does that look.

**Comment by nhazekam** [comment]
Segfaults on no batch options. I am making a change.

**Comment by btovar** [comment]
Nick, the general approach seems fine to me. Merge when ready.

**Comment by nhazekam** [comment]
Addresses #1366

**Pull request merged**
