### PR TITLE
Makeflow directives

### PR DESCRIPTION
**Pull request by nhazekam**
This introduces directives, name courtesy of @btovar, which provides a flexible way to specify Makeflow specific information and parse out more tokens for a given type of directive. In this pull request .RESOURCE and .SIZE were added, with the possibility of .MOUNT or others being added later.

@btovar @dthain give it a look and let me know what you think.

### CODE REVIEW

**Comment by dthain** [comment]
A quick sanity check -- Where we find it necessary to extend the Makeflow syntax, it should not unduly conflict with existing Make syntax.

Is this consistent with the use of directives like `.FORCE` in GNU Make?

**Comment by nhazekam** [comment]
They don't appear to be the same. .FORCE and .PHONY are ways of forcing rules to run or always made (simplification), whereas the directives in this case are used to inform Makeflow of information about nodes, files, or the DAG in general. They do not affect if/when rules are executed.

**Comment by btovar** [comment]
But they are consistent, in the sense that they inform the make program, rather than the dag. This is why we chose the . (dot) notation.

**Comment by dthain** [comment]
Ok, Ben addressed my concern.

**Comment by btovar** [comment]
.RESOURCE notaresource 123 should generate an error.

.NOTADIRECTIVE
does generate an error, but the error message has garbage, probably a memory error.

.RESOURCE CORES aword
works, but it shouldn't, as we are expecting a number.

**Comment by nhazekam** [comment]
I will address the second and see if I can make the error more clear. As for the first and the third, .RESOURCE uses the current logic for variables, which allows both. I can add handling that only permits certain resource specifications {CORES, DISK, MEMORY} and types{ints}, but it currently doesn't as variables are generic.

**Comment by btovar** [comment]
Since .RESOURCE SOMETHING has more of a syntax flavor, let's generate an error for those we do not recognize.

**Comment by nhazekam** [comment]
@btovar I add more syntax information and also added a couple of tests. let me know if this is sufficient or not quite the expected cases.

**Comment by btovar** [comment]
Nick, ready to merge if you are.

**Comment by nhazekam** [comment]
Resolve #1383

**Pull request merged**
