### PR TITLE
VINE: add miscellaneous plotting tools

### PR DESCRIPTION
**Pull request by BarrySlyDelgado**
## Proposed Changes

This adds two tools. One is `vine_plot_compose` which is useful for creating a series of plots in one png. pdf. etc.. using one or more transaction logs. i.e it is useful to use when comparing runs. like so:
example

The second tool is `vine_plot_animate` which creates an animation of a single plot which is the `--data-exg` plot from `vine_plot_compose` like so:
anim

These were originally used to create figures for the HEP paper but can be useful in the general case and for debugging i.e. #3851 

## Merge Checklist

The following items must be completed before PRs can be merge.
Check these off to verify you have completed all steps.

- [x] `make test`       Run local tests prior to pushing.
- [x] `make format`     Format source code to comply with lint policies. Note that some lint errors can only be resolved manually (e.g., Python)
- [x] `make lint`       Run lint on source code prior to pushing.
- [x] Manual Update     Update the manual to reflect user-visible changes.
- [x] Type Labels       Select a github label for the type: bugfix, enhancement, etc.
- [x] Product Labels    Select a github label for the product: TaskVine, Makeflow, etc.
- [x] PR RTM            Mark your PR as ready to merge.

### CODE REVIEW

**Comment by dthain** [comment]
Those look great!  Please add some discussion and sample outputs to the appropriate place in the manual.

**Comment by dthain** [comment]
A small change but will avoid problems in the future: please rename `vine_plot_animate` to `vine_transfer_plot_animate` since it just produces that one thing.

**Comment by dthain** [comment]
RTM?

**Comment by BarrySlyDelgado** [comment]
Yes, RTM.

**Review by dthain — APPROVED** [review]

**Pull request merged**
