### PR TITLE
TaskVine: fix FunctionCall API, update example, and add test

### PR DESCRIPTION
**Pull request by tphung3**
This PR fixes issue #3417, updates example code, and adds test code.
Do all files with prefix `TR_` get tested? I'm not sure. The test code is very similar to `python_task` though.

### CODE REVIEW

**Review by dthain — APPROVED** [review]
Thanks - Having a good test goes a long way towards preventing these sorts of problems.

**Comment by dthain** [comment]
Possibly `import ndcctools.poncho` instead of `import poncho` inside of `manager.py` ?

**Comment by tphung3** [comment]
I think the python version inside the container is 3.6, while poncho uses `ast.unparse` which is a feature for python 3.9. I'm tracking down where python is installed.

**Comment by tphung3** [comment]
> Possibly `import ndcctools.poncho` instead of `import poncho` inside of `manager.py` ?

Your are right this will work for tests that don't use the serverless feature.

**Comment by tphung3** [comment]
This PR is RTM.

**Review by dthain — APPROVED** [review]

**Pull request merged**
