### PR TITLE
Add option to compile with -fsanitize=address and -fsanitize=undefined

### PR DESCRIPTION
**Pull request by trshaffer**
This is for #1286.

I added a new option to the `configure` script to compile with these options. N.B. that GCC>=4.8 is required. If configured as

    ./configure --sanitize

all programs will exit with non-zero status and print details in the case of leaks. The numerous changed files are due to test scripts that compile their own code. Extra linker flags are required for those tests, so I passed them through an environment variable. I'm not sure if this is the most correct way to do it, though

### CODE REVIEW

**Comment by trshaffer** [comment]
@nhazekam just pointed out that `-fsanitize=undefined` seems to be unsupported on GCC 4.8.2

**Comment by batrick** [comment]
Go ahead and turn on `--sanitize` as well for `--debug`, in `configure`.

**Comment by nhazekam** [comment]
@btovar Was this merge ready? I think we had concerns about compiler versions compatibility.

**Comment by nhazekam** [comment]
@trshaffer @btovar can we revert and have Tim rollback to c199604 instead of 5098db9. This would not add sanitize to the debug options in config, the user has to explicitly add -fsanitize.

**Pull request merged**
