### PR TITLE
small fixes for resource monitor histograms

### PR DESCRIPTION
**Pull request by btovar**

### CODE REVIEW

**Comment by btovar** [comment]
.RESOURCE notaresource 123   should generate an error.

.NOTADIRECTIVE 
does generate an error, but the error message has garbage, probably a memory error.

.RESOURCE CORES aword
works, but it shouldn't, as we are expecting a number.

**Comment by nhazekam** [comment]
@btovar Is this intended for #1399 ?

**Comment by btovar** [comment]
no... why?

**Comment by nhazekam** [comment]
.RESOURCE is not integrated in master or this pull request. These may be issues with the referenced pull request, but I don't think this applies to RM Histograms.

**Comment by btovar** [comment]
My mistake, I commented in the wrong pr.

**Pull request merged**
