### PR TITLE
makeflow_blasr python script and README

### PR DESCRIPTION
**Pull request by kangkangli**
This is the makeflow_blasr python script and READEM documentation.

### CODE REVIEW

**Comment by nhazekam** [comment]
<h3>Makeflow BWA</h3>
<p>
You will find sample data for this guide <a href="
http://ccl.cse.nd.edu/software/manuals/install.html">here</a>.

<table>
<tr>
<th>Software</th><th>Version</th><th>Must be present in environment
variable</th>
</tr>
<tr>
<td><a href="http://bio-bwa.sourceforge.net/
">BWA</a></td><td>5+</td><td>PATH</td>
</tr>
</table>

The following files are provided:
<ul>
<li><tt>XTC.tar.bz2</tt>: MD trajectory files for Alanine Dipeptide</li>
<li><tt>native.pdb</tt>: Conformation of the "native" structure</li>
<li><tt>AtomIndices.dat</tt>: atoms to use</li>
</ul>

<p>
Copy makeflow_bwa from cctools/apps/makeflow_bwa/makeflow_bwa to the
execution location.
<p>
Run
<code>% ./makeflow_bwa --ref test_ref.fa --fastq test_query.fq --output_SAM
output.sam --algoalign {backtrack|bwasw|mem} --makeflow Makeflow --verbose
</code>

You should now see the verbose logging explain what is happening:
<code>INFO: Verbose output.
INFO: Partition Size : 50000
INFO: Writing Partitioning Script to : fastq_reduce
INFO: fastq_reduce made executable
INFO: Writing Joining Script to : cat_bwa
INFO: cat_bwa made executable
INFO: Searching PATH for BWA
INFO: BWA found locally
INFO: Writing Makeflow to : Makeflow
INFO: Counting Number of Partitions
INFO: Current Number of Partitions : 10
INFO: Current Number of Partitions : 20
INFO: Current Number of Partitions : 30
INFO: Total Number of Partitions : 36
INFO: Writing Partitioning Rules
INFO: Writing Indexing Rules
INFO: Writing BWA mem Rules
INFO: Writing Joining Rules
</code>

**Comment by dthain** [comment]
Did this get pasted in the wrong place?

**Comment by nhazekam** [comment]
Yes absolutely. I thought this was a different chain I was working on with
KangKang. I will remove it and fix that. Apologies.

Nick

**Comment by kangkangli** [comment]
update the  version of makeflow_blasr in github, in consistent with other version in ND_bioapps. @nhazekam

**Comment by nhazekam** [comment]
Two things:

1. Move --num_seq in options from blasr option to makeflow option. This will make it consistent.

2. It looks as though you have updated the hdf5 library name, but the rules and the makeflow export still use the local name ./lib. This needs to be corrected.

**Comment by dthain** [comment]
@nhazekam how does this look so far?

**Comment by nhazekam** [comment]
Looks good to me. Its ready to be merged.

**Pull request merged**
