### PR TITLE
Parrot Packaging: Detect File Size

### PR DESCRIPTION
**Pull request by hmeng-19**
Currently, `parrot_package_create` does not keep the file size info when the copy degree of a file is metadata-level copy, because using `truncate` system call on an empty file on AFS results in the `st_blocks` field becomes non-zero, which makes it difficult to determine whether a file is really empty or not. 

This PR is an attempt to keep the file size information. This may cause some applications involving AFS file accesses to break.

### CODE REVIEW

**Comment by hmeng-19** [comment]
@trshaffer , try to use the parrot packaging tool in this PR to reproduce your python3 applications. It should fix the problem.
Let me know if it works for you.

**Comment by hmeng-19** [comment]
@dthain , PTAL.

**Comment by dthain** [comment]
If this works for our common use cases today, then that's fine.

As a long-term measure, I'm not sure that I would rely upon the semantics of `st_blocks`.  Different filesystems seem to interpret that field in different ways.

**Comment by dthain** [comment]
@trshaffer Does this PR work for the python3 use case?

**Comment by dthain** [comment]
@trshaffer need your thumbs up or down on this one.

**Comment by trshaffer** [comment]
:+1:
I can start Python 3 under this branch

**Pull request merged**
