### PR TITLE
Factory Fixes

### PR DESCRIPTION
**Pull request by dthain**
Fixes two problems that were preventing correct operation at Arizona:
* -N batch name cannot be more than 15 characters
* scratch directory of factory needs to be on a shared filesystem.

### CODE REVIEW

**Comment by btovar** [comment]
This changes look good. Are they ready to be merged?

**Comment by dthain** [comment]
Hold on

**Comment by dthain** [comment]
Need to fix a build issue and test quickly at the crc.

**Comment by dthain** [comment]
Ok, we are good now.

**Comment by btovar** [comment]
Will wait for blue water fix to make the next bug release.

**Pull request merged**
