### PR TITLE
Python interface for wq factory

### PR DESCRIPTION
**Pull request by btovar**
@trshaffer From your code I renamed it to work_queue.Factory, made a distinction between command line only and config file options, and made some variables and functions class attributes.

Let me know if it still works as you intended.

### CODE REVIEW

**Comment by btovar** [comment]
@trshaffer, Tim, does this pr looks good to you?

**Comment by trshaffer** [comment]
@btovar it looks like the options aren't translating between dashes and underscores when going from Python identifiers to JSON option names?

**Comment by btovar** [comment]
Let me see...

**Comment by btovar** [comment]
@trshaffer  could you give it another try?

**Pull request merged**
