### PR TITLE
vine factory:always use manager.name as fallback when no host:port is available

### LINKED ISSUE #3999: vine: in-context factory uses wrong hosturl for remote workers when given manager object as argument.
Depending on how you create a factory in your application, if using condor/sge as the batch_type it may create the worker command pointing to localhost, which will not reach the manager when it is on a remote worker.

If the factory is created like this, as in some of our examples: `f = vine.Factory(manager=m)` the problem occurs.

If the factory is created like this: `f = vine.Factory(manager_name="x")` where x is the name used when creating the manager, it will work properly.

### PR DESCRIPTION
**Pull request by btovar**
Fix #3999 

## Proposed Changes

Give an overall description of the changes, along with the context and motivation.
Mention relevant issues and pull requests as needed.

## Merge Checklist

The following items must be completed before PRs can be merged.
Check these off to verify you have completed all steps.

- [ ] `make test`       Run local tests prior to pushing.
- [ ] `make format`     Format source code to comply with lint policies. Note that some lint errors can only be resolved manually (e.g., Python)
- [ ] `make lint`       Run lint on source code prior to pushing.
- [ ] Manual Update:     Update the manual to reflect user-visible changes.
- [ ] Type Labels:       Select a github label for the type: bugfix, enhancement, etc.
- [ ] Product Labels:    Select a github label for the product: TaskVine, Makeflow, etc.
- [ ] PR RTM:            Mark your PR as ready to merge.

### CODE REVIEW

**Comment by colinthomas-z80** [comment]
Make sure this works even when both manager name and object are specified. like:

`Factory(manager=m, manager_name="xyz")`

**Comment by btovar** [comment]
localhost:port should only be set when using batch_type local.  Is this not the case?

**Comment by colinthomas-z80** [comment]
Yeah the problem I brought up in the issue was that when the manager object is passed to the factory it always invokes the worker with `localhost:port` regardless of batch type or other kwargs. So condor workers would not connect

**Comment by colinthomas-z80** [comment]
It might be that I was creating the factory giving only the manager object as an argument, then modifying the factory object afterwards like `f.batch_type = "condor"`. So the batch type gets changed but it does not modify the manager_hostport

**Comment by colinthomas-z80** [comment]
Could we stop using localhost and always use a proper hostname so that local and remote workers can resolve if batch_type gets changed on the fly?

**Comment by btovar** [comment]
I'm more inclined to forbid changing the batch type and manager host port after __init__. This would reflect what the `vine_factory` command line does.  We should only update parameters that correspond to fields in the config file once the factory is created. The localhost:port default is meant to be user friendly for the introductory examples.

**Comment by colinthomas-z80** [comment]
Sounds good to me.

**Comment by colinthomas-z80** [comment]
yes!

**Review by colinthomas-z80 — APPROVED** [review]

**Pull request merged**
