### PR TITLE
Release/5.4

### PR DESCRIPTION
**Pull request by nhazekam**
Back ports changes @dthain made to cleanly build on Blue Waters, as well as adds blue_waters to the batch_job interface.

### CODE REVIEW

**Comment by btovar** [comment]
Nick, is this pr you want me to add?

Note that it failed on all autobuild machines.

**Comment by nhazekam** [comment]
I am working on the failures, but yes this is. I am building it off of 5.4 so it can be bumped more easily.

**Comment by nhazekam** [comment]
Thanks for tracking down that issue @btovar

**Comment by nhazekam** [comment]
@btovar Can this be closed as the changes exist in ccl/release/5.4 now?

**Comment by btovar** [comment]
Yes.

**Pull request closed without merging**
