### PR TITLE
Vine api rename

### PR DESCRIPTION
**Pull request by btovar**
For #3004 

specify to add, set, and enable. 
I still need to go through each exposed function and maybe propose a better name (e.g. more regular names). But I think we can merge this one before the better names in order to reduce conflicts with other prs.

### CODE REVIEW

**Comment by dthain** [comment]
I am impressed that this passes CI on the first try!

**Comment by btovar** [comment]
It seems we need better tests, ha!

**Comment by btovar** [comment]
ok to merge?

**Comment by dthain** [comment]
Looks good!

**Pull request merged**
