### PR TITLE
Turn some errors into resource exhaustion signals

### PR DESCRIPTION
**Pull request by btovar**
1) Keep last related error.
2) Capture write with ld preload.
3) Quit on no space and no file descriptors.

### CODE REVIEW

**Comment by dthain** [comment]
Maybe I'm reading this incorrectly, but it looks to me like every errno from write is returned to the supervisor process, which then considers any errno at all to signal resource exhaustion.  I suspect this is a little too aggressive, since write does occasionally return EINTR, EAGAIN, or perhaps EBADF if the user does strange things.

I think you want to only consider it resource exhaustion when you explicitly get known errnos such as ENOSPC and EMFILE.  (or is it ENFILE?  I always have to look those two up.)

**Comment by btovar** [comment]
@dthain, you are correct. The last two commits should address your comments.

**Comment by btovar** [comment]
Do not merge yet, working on a bug.

**Comment by btovar** [comment]
@dthain ready now. (autobuild failure is fixed by one of your commits already in master)

**Pull request merged**
