### PR TITLE
change cache flags for tarballs from always to never

### PR DESCRIPTION
**Pull request by tphung3**
Tarballs should not be cached I think

### CODE REVIEW

**Comment by dthain** [comment]
I'm confused -- don't we want the tarballs to be widely replicated and stored between runs?

**Comment by btovar** [comment]
Yes, I think they should be cached. In fact that's one of the main points this example shows: expensive to transfer of files is only done once per worker.

**Comment by tphung3** [comment]
We want the thing that the tarball unpacks to be cached, not the tarball right?

**Comment by dthain** [comment]
Ah, I seem to recall that we had some difficulty caching and sharing the output of a mini-task.  @colinthomas-z80 does this work now?

**Comment by btovar** [comment]
For tarballs we never want to share the output, as expanded it may have thousands of files. Mini task also specialize to the task sandbox.

**Comment by colinthomas-z80** [comment]
@btovar if we refer to vine_file.c, taking vine_declare_untar as an example, does specifying caching/sharing flags actually do anything at all?

**Comment by tphung3** [comment]
> For tarballs we never want to share the output, as expanded it may have thousands of files. Mini task also specialize to the task sandbox.

But the untar minitask on its own will inflate those thousands of files anyway right?

**Comment by btovar** [comment]
@colinthomas-z80  The flags given to the mini task are the flags that it's output gets. I don't think the mini task gets any flags for itself.

@tphung3 Yes, but it will do so locally. We don't have to send all those files uncompressed over the network.

**Comment by tphung3** [comment]
@btovar I sort of see what you are saying. So we cache the output (1000s of files) of a minitask on a worker, but share (via peer transfer) the input (tarball) of that minitask to other workers.

**Comment by btovar** [comment]
Yes, I think that's the current idea. I know Colin is trying to figure out how to share the output of a mini task when it makes sense, which should produce some interesting usage patterns.

**Pull request closed without merging**
