### PR TITLE
Change the structure of the cctools binary dir

### PR DESCRIPTION
**Pull request by hmeng-19**
The changes are:
mv cctools/doc to cctools/share/doc/cctools
mv config.mk to cctools/share/doc/cctools/config.mk
remove cctools/etc
mv cctools/lib/* to cctools/lib/cctools/* (except for cctools/lib/perl5 and cctools/lib/python*)

### CODE REVIEW

**Comment by dthain** [comment]
The Makefile is the wrong place to make these changes.

If a user does a simple `configure --prefix X` then we want the installed package to have the conventional directories of X/bin, X/doc, X/etc and so forth.  

If RPMs require these directories to be different, then the changes should be made by the RPM build process *after* `make install`

**Comment by hmeng-19** [comment]
@dthain , once we agreed that the structure of our rpm follows the unix filesystem hierarchy standard, I did not see why not change the binary code of cctools?

**Comment by dthain** [comment]
As we discussed today, please get together with @btovar and @pivie to discuss this.

The main idea is that `make install` should do a simple cross-platform installation, since we expect it to work on Linux, Windows, MacOS, Solaris, or whatever comes next.  If there are locations that are specific to Linux RPMs, OSX portfiles, etc, then those locations should be arranged by the RPM, portfile, or other platform specific tool.

**Comment by btovar** [comment]
We'll keep discussing on our list.

**Pull request closed without merging**
