### PR TITLE
Structure for poncho serverles

### PR DESCRIPTION
**Pull request by BarrySlyDelgado**
Added the things needed for poncho_package_serverless. Needs addition of Network Function and Coprocess from @David-Simonetti-ND

### CODE REVIEW

**Comment by btovar** [comment]
@BarrySlyDelgado Looks good! Ready to merge?

**Comment by David-Simonetti-ND** [comment]
#2888 includes all of Barry's commits from here, I think this pr can be closed.

**Comment by BarrySlyDelgado** [comment]
@btovar Secoding what David said.

**Comment by BarrySlyDelgado** [comment]
@btovar Secoding what David said.

**Pull request closed without merging**
