### PR TITLE
Makeflow Sandbox Mode

### PR DESCRIPTION
**Pull request by dthain**
First pass at local execution in a sandbox.

### CODE REVIEW

**Comment by dthain** [comment]
@nkremerh @nhazekam please take a look and see if this is on the right track.

**Comment by dthain** [comment]
Still thinking about this one.  Is sandbox better off as a batch type, or as a kind of a wrapper?

**Comment by btovar** [comment]
Given the current state of the code, a wrapper will be most useful. We can reuse it in the other batch systems easily, specially LOCAL.

Also, we can have a --strict flag, in which all task should run in sandbox mode. We can then advice the user that --strict is the way to go.

**Comment by btovar** [comment]
This is of course, assuming we will be able to chain wrappers, which I think you want to do in the new json code.

**Comment by dthain** [comment]
Updated to bring into sync with master.

**Comment by dthain** [comment]
Closing this as the wrong approach.

**Pull request closed without merging**
