### PR TITLE
Update install guide to include to Spack instructions.

### PR DESCRIPTION
**Pull request by tjuedema**
Updated install instructions to include steps for installing CCTools via Spack for part of Issue #2164.

### CODE REVIEW

**Comment by dthain** [comment]
That's fine, but also include some information about Spack, why you might choose that as the installation method, links to installing Spack itself, etc...

**Comment by dthain** [comment]
Ok, when I follow these instructions, I get the following error installing expat
deep in the dependency chain. Do you get the same error? 

```
[dthain@cclws15 /tmp]$ 
[dthain@cclws15 /tmp]$ bash
bash-4.2$ git clone https://github.com/spack/spack.git
Cloning into 'spack'...
remote: Enumerating objects: 4669, done.
remote: Counting objects: 100% (4669/4669), done.
remote: Compressing objects: 100% (2221/2221), done.
remote: Total 173130 (delta 328), reused 4434 (delta 323), pack-reused 168461
Receiving objects: 100% (173130/173130), 65.23 MiB | 3.76 MiB/s, done.
Resolving deltas: 100% (76543/76543), done.
bash-4.2$ . spack/share/spack/setup-env.sh
bash-4.2$ spack install cctools
==> Installing pkgconf
==> Searching for binary cache of pkgconf
==> No binary for pkgconf found: installing from source
==> Fetching http://distfiles.dereferenced.org/pkgconf/pkgconf-1.6.3.tar.xz
######################################################################## 100.0%
==> Staging archive: /tmp/dthain/spack-stage/pkgconf-1.6.3-ksqeefb4sfmoplzlelwxsyowlrpiutyd/pkgconf-1.6.3.tar.xz
==> Created stage in /tmp/dthain/spack-stage/pkgconf-1.6.3-ksqeefb4sfmoplzlelwxsyowlrpiutyd
==> No patches needed for pkgconf
==> Building pkgconf [AutotoolsPackage]
==> Executing phase: 'autoreconf'
==> Executing phase: 'configure'
==> Executing phase: 'build'
==> Executing phase: 'install'
==> Successfully installed pkgconf
  Fetch: 0.53s.  Build: 4.97s.  Total: 5.50s.
[+] /tmp/spack/opt/spack/linux-rhel7-sandybridge/gcc-4.8.5/pkgconf-1.6.3-ksqeefb4sfmoplzlelwxsyowlrpiutyd
==> Installing ncurses
==> Searching for binary cache of ncurses
==> No binary for ncurses found: installing from source
==> Fetching http://ftpmirror.gnu.org/ncurses/ncurses-6.1.tar.gz
######################################################################## 100.0%
==> Staging archive: /tmp/dthain/spack-stage/ncurses-6.1-svjqg4mg7uhuoljjb66sibreq56brrgj/ncurses-6.1.tar.gz
==> Created stage in /tmp/dthain/spack-stage/ncurses-6.1-svjqg4mg7uhuoljjb66sibreq56brrgj
==> No patches needed for ncurses
==> Building ncurses [AutotoolsPackage]
==> Executing phase: 'autoreconf'
==> Executing phase: 'configure'
==> Executing phase: 'build'
==> Executing phase: 'install'
==> Successfully installed ncurses
  Fetch: 0.54s.  Build: 1m 30.59s.  Total: 1m 31.13s.
[+] /tmp/spack/opt/spack/linux-rhel7-sandybridge/gcc-4.8.5/ncurses-6.1-svjqg4mg7uhuoljjb66sibreq56brrgj
==> Installing readline
==> Searching for binary cache of readline
==> No binary for readline found: installing from source
==> Fetching http://ftpmirror.gnu.org/readline/readline-8.0.tar.gz
######################################################################## 100.0%
==> Staging archive: /tmp/dthain/spack-stage/readline-8.0-35qbzsazphgea5wdz7bn5uhkw5zc7o44/readline-8.0.tar.gz
==> Created stage in /tmp/dthain/spack-stage/readline-8.0-35qbzsazphgea5wdz7bn5uhkw5zc7o44
==> No patches needed for readline
==> Building readline [AutotoolsPackage]
==> Executing phase: 'autoreconf'
==> Executing phase: 'configure'
==> Executing phase: 'build'
==> Executing phase: 'install'
==> Successfully installed readline
  Fetch: 0.57s.  Build: 10.34s.  Total: 10.91s.
[+] /tmp/spack/opt/spack/linux-rhel7-sandybridge/gcc-4.8.5/readline-8.0-35qbzsazphgea5wdz7bn5uhkw5zc7o44
==> Installing gdbm
==> Searching for binary cache of gdbm
==> No binary for gdbm found: installing from source
==> Fetching http://ftpmirror.gnu.org/gdbm/gdbm-1.18.1.tar.gz
######################################################################## 100.0%
==> Staging archive: /tmp/dthain/spack-stage/gdbm-1.18.1-wbpk2zmhvg3dbrxe6v66vzaygl26gigh/gdbm-1.18.1.tar.gz
==> Created stage in /tmp/dthain/spack-stage/gdbm-1.18.1-wbpk2zmhvg3dbrxe6v66vzaygl26gigh
==> No patches needed for gdbm
==> Building gdbm [AutotoolsPackage]
==> Executing phase: 'autoreconf'
==> Executing phase: 'configure'
==> Executing phase: 'build'
==> Executing phase: 'install'
==> Successfully installed gdbm
  Fetch: 1.03s.  Build: 8.48s.  Total: 9.51s.
[+] /tmp/spack/opt/spack/linux-rhel7-sandybridge/gcc-4.8.5/gdbm-1.18.1-wbpk2zmhvg3dbrxe6v66vzaygl26gigh
==> Installing perl
==> Searching for binary cache of perl
==> No binary for perl found: installing from source
==> Fetching http://www.cpan.org/src/5.0/perl-5.30.0.tar.gz
######################################################################## 100.0%
==> Fetching http://search.cpan.org/CPAN/authors/id/M/MI/MIYAGAWA/App-cpanminus-1.7042.tar.gz
######################################################################## 100.0%
==> Staging archive: /tmp/dthain/spack-stage/perl-5.30.0-uch57hjnvpvza3fq4ynajyrx2ac6l5mu/perl-5.30.0.tar.gz
==> Created stage in /tmp/dthain/spack-stage/perl-5.30.0-uch57hjnvpvza3fq4ynajyrx2ac6l5mu
==> Staging archive: /tmp/dthain/spack-stage/resource-cpanm-uch57hjnvpvza3fq4ynajyrx2ac6l5mu/App-cpanminus-1.7042.tar.gz
==> Created stage in /tmp/dthain/spack-stage/resource-cpanm-uch57hjnvpvza3fq4ynajyrx2ac6l5mu
==> Moving resource stage
	source : /tmp/dthain/spack-stage/resource-cpanm-uch57hjnvpvza3fq4ynajyrx2ac6l5mu/spack-src/
	destination : /tmp/dthain/spack-stage/perl-5.30.0-uch57hjnvpvza3fq4ynajyrx2ac6l5mu/spack-src/cpanm/cpanm
==> No patches needed for perl
==> Building perl [Package]
==> Executing phase: 'configure'
==> Executing phase: 'build'
==> Executing phase: 'install'
==> Successfully installed perl
  Fetch: 1.69s.  Build: 2m 18.27s.  Total: 2m 19.96s.
[+] /tmp/spack/opt/spack/linux-rhel7-sandybridge/gcc-4.8.5/perl-5.30.0-uch57hjnvpvza3fq4ynajyrx2ac6l5mu
==> Installing zlib
==> Searching for binary cache of zlib
==> No binary for zlib found: installing from source
==> Fetching http://zlib.net/fossils/zlib-1.2.11.tar.gz
######################################################################## 100.0%
==> Staging archive: /tmp/dthain/spack-stage/zlib-1.2.11-adbduglmlivk4yrvuczlhxicfloq34zr/zlib-1.2.11.tar.gz
==> Created stage in /tmp/dthain/spack-stage/zlib-1.2.11-adbduglmlivk4yrvuczlhxicfloq34zr
==> No patches needed for zlib
==> Building zlib [Package]
==> Executing phase: 'install'
==> Successfully installed zlib
  Fetch: 0.48s.  Build: 2.44s.  Total: 2.92s.
[+] /tmp/spack/opt/spack/linux-rhel7-sandybridge/gcc-4.8.5/zlib-1.2.11-adbduglmlivk4yrvuczlhxicfloq34zr
==> Installing openssl
==> Searching for binary cache of openssl
==> No binary for openssl found: installing from source
==> Fetching http://www.openssl.org/source/openssl-1.1.1d.tar.gz
######################################################################## 100.0%
==> Staging archive: /tmp/dthain/spack-stage/openssl-1.1.1d-5ikwr3egwtkvfvrm4qusnlmmui7qmaow/openssl-1.1.1d.tar.gz
==> Created stage in /tmp/dthain/spack-stage/openssl-1.1.1d-5ikwr3egwtkvfvrm4qusnlmmui7qmaow
==> No patches needed for openssl
==> Building openssl [Package]
==> Executing phase: 'install'
==> Successfully installed openssl
  Fetch: 0.87s.  Build: 3m 46.81s.  Total: 3m 47.68s.
[+] /tmp/spack/opt/spack/linux-rhel7-sandybridge/gcc-4.8.5/openssl-1.1.1d-5ikwr3egwtkvfvrm4qusnlmmui7qmaow
==> Installing libiconv
==> Searching for binary cache of libiconv
==> No binary for libiconv found: installing from source
==> Fetching https://ftpmirror.gnu.org/libiconv/libiconv-1.16.tar.gz
######################################################################## 100.0%
==> Staging archive: /tmp/dthain/spack-stage/libiconv-1.16-fshkrxuytnkictkqdes555qkiy4d6qfj/libiconv-1.16.tar.gz
==> Created stage in /tmp/dthain/spack-stage/libiconv-1.16-fshkrxuytnkictkqdes555qkiy4d6qfj
==> No patches needed for libiconv
==> Building libiconv [AutotoolsPackage]
==> Executing phase: 'autoreconf'
==> Executing phase: 'configure'
==> Executing phase: 'build'
==> Executing phase: 'install'
==> Successfully installed libiconv
  Fetch: 1.56s.  Build: 16.13s.  Total: 17.69s.
[+] /tmp/spack/opt/spack/linux-rhel7-sandybridge/gcc-4.8.5/libiconv-1.16-fshkrxuytnkictkqdes555qkiy4d6qfj
==> Installing diffutils
==> Searching for binary cache of diffutils
==> No binary for diffutils found: installing from source
==> Fetching https://ftpmirror.gnu.org/diffutils/diffutils-3.7.tar.xz
######################################################################## 100.0%
==> Staging archive: /tmp/dthain/spack-stage/diffutils-3.7-wc3iq526gip6liiotkqtn42dtpmdmjsf/diffutils-3.7.tar.xz
==> Created stage in /tmp/dthain/spack-stage/diffutils-3.7-wc3iq526gip6liiotkqtn42dtpmdmjsf
==> No patches needed for diffutils
==> Building diffutils [AutotoolsPackage]
==> Executing phase: 'autoreconf'
==> Executing phase: 'configure'
==> Executing phase: 'build'
==> Executing phase: 'install'
==> Successfully installed diffutils
  Fetch: 1.14s.  Build: 24.91s.  Total: 26.05s.
[+] /tmp/spack/opt/spack/linux-rhel7-sandybridge/gcc-4.8.5/diffutils-3.7-wc3iq526gip6liiotkqtn42dtpmdmjsf
==> Installing bzip2
==> Searching for binary cache of bzip2
==> No binary for bzip2 found: installing from source
==> Fetching https://sourceware.org/pub/bzip2/bzip2-1.0.8.tar.gz
######################################################################## 100.0%
==> Staging archive: /tmp/dthain/spack-stage/bzip2-1.0.8-e6sgjufitorv6iw5kuq3ysay6x4ba6s3/bzip2-1.0.8.tar.gz
==> Created stage in /tmp/dthain/spack-stage/bzip2-1.0.8-e6sgjufitorv6iw5kuq3ysay6x4ba6s3
==> Ran patch() for bzip2
==> Building bzip2 [Package]
==> Executing phase: 'install'
==> Successfully installed bzip2
  Fetch: 2.55s.  Build: 2.25s.  Total: 4.80s.
[+] /tmp/spack/opt/spack/linux-rhel7-sandybridge/gcc-4.8.5/bzip2-1.0.8-e6sgjufitorv6iw5kuq3ysay6x4ba6s3
==> Installing libbsd
==> Searching for binary cache of libbsd
==> No binary for libbsd found: installing from source
==> Fetching https://libbsd.freedesktop.org/releases/libbsd-0.9.1.tar.xz
######################################################################## 100.0%
==> Staging archive: /tmp/dthain/spack-stage/libbsd-0.9.1-z6e7nbrszqx7gq364qf2bxdof63h7sme/libbsd-0.9.1.tar.xz
==> Created stage in /tmp/dthain/spack-stage/libbsd-0.9.1-z6e7nbrszqx7gq364qf2bxdof63h7sme
==> No patches needed for libbsd
==> Building libbsd [AutotoolsPackage]
==> Executing phase: 'autoreconf'
==> Executing phase: 'configure'
==> Executing phase: 'build'
==> Executing phase: 'install'
==> Successfully installed libbsd
  Fetch: 0.69s.  Build: 7.23s.  Total: 7.91s.
[+] /tmp/spack/opt/spack/linux-rhel7-sandybridge/gcc-4.8.5/libbsd-0.9.1-z6e7nbrszqx7gq364qf2bxdof63h7sme
==> Installing expat
==> Searching for binary cache of expat
==> No binary for expat found: installing from source
==> Fetching https://github.com/libexpat/libexpat/releases/download/R_2_2_9/expat-2.2.9.tar.bz2
######################################################################## 100.0%
==> Staging archive: /tmp/dthain/spack-stage/expat-2.2.9-3ec5cwohx5pnfqsyp3nzr5s672yl4i6y/expat-2.2.9.tar.bz2
==> Created stage in /tmp/dthain/spack-stage/expat-2.2.9-3ec5cwohx5pnfqsyp3nzr5s672yl4i6y
==> No patches needed for expat
==> Building expat [AutotoolsPackage]
==> Executing phase: 'autoreconf'
==> Executing phase: 'configure'
==> Error: ProcessError: Command exited with status 1:
    '/tmp/dthain/spack-stage/expat-2.2.9-3ec5cwohx5pnfqsyp3nzr5s672yl4i6y/spack-src/configure' '--prefix=/tmp/spack/opt/spack/linux-rhel7-sandybridge/gcc-4.8.5/expat-2.2.9-3ec5cwohx5pnfqsyp3nzr5s672yl4i6y' '--with-libbsd'

1 error found in build log:
     135    checking for sys/param.h... yes
     136    checking for getpagesize... yes
     137    checking for working mmap... yes
     138    checking for docbook2x-man... no
     139    checking for db2x_docbook2man... no
     140    checking for docbook2man... docbook2man
  >> 141    configure: error: Your local docbook2man was found to work with SGM
            L rather
     142      than XML. Please install docbook2X and use variable DOCBOOK_TO_MA
            N to point
     143      configure to command docbook2x-man of docbook2X.
     144      Or use DOCBOOK_TO_MAN="xmlto man --skip-validation" if you have x
            mlto around.
     145      You can also configure using --without-docbook if you can do with
            out a man
     146      page for xmlwf.

See build log for details:
  /tmp/dthain/spack-stage/expat-2.2.9-3ec5cwohx5pnfqsyp3nzr5s672yl4i6y/spack-build-out.txt

bash-4.2$ 
```

**Comment by tjuedema** [comment]
Can confirm. I get the same error on cclws18 in /tmp regardless if I set up Spack using the linked instructions, or set up env variables using the alternative install instructions in the docs.

However, I do not get this error when I install Spack and CCTools in /scratch365 on crcfe01.

**Comment by dthain** [comment]
It seems like our users are likely to hit this roadblock, so please look into some options.

Maybe we can change the expat recipe to suppress doc generation?
Maybe cctools can depend upon an alternate build of expat?
Wouldn't hurt to ask the Spack experts about best practices for this sort of thing...

**Comment by tjuedema** [comment]
Commenting this in just to keep track of the fix process. We can generate the dependency tree that Spack uses when installing CCTools:

```sh
[tjuedema@cclws18 spack-stage]$ spack spec cctools
Input spec                                                                                                                                                          
--------------------------------                                                                                                                                                     
cctools                                                                                                                                                                                     
                                                                                                                     
Concretized                                                                                                          
--------------------------------                                                                                     
cctools@7.0.18%gcc@4.8.5 arch=linux-rhel7-ivybridge
    ^openssl@1.1.1d%gcc@4.8.5+systemcerts arch=linux-rhel7-ivybridge
        ^perl@5.30.0%gcc@4.8.5+cpanm+shared+threads arch=linux-rhel7-ivybridge
            ^gdbm@1.18.1%gcc@4.8.5 arch=linux-rhel7-ivybridge
                ^readline@8.0%gcc@4.8.5 arch=linux-rhel7-ivybridge
                    ^ncurses@6.1%gcc@4.8.5~symlinks~termlib arch=linux-rhel7-ivybridge
                        ^pkgconf@1.6.3%gcc@4.8.5 arch=linux-rhel7-ivybridge
        ^zlib@1.2.11%gcc@4.8.5+optimize+pic+shared arch=linux-rhel7-ivybridge
    ^python@2.7.16%gcc@4.8.5+bz2+ctypes+dbm+lzma~nis~optimizations+pic+pyexpat+pythoncmd+readline+shared+sqlite3+ssl~
        ^bzip2@1.0.8%gcc@4.8.5+shared arch=linux-rhel7-ivybridge
            ^diffutils@3.7%gcc@4.8.5 arch=linux-rhel7-ivybridge
                ^libiconv@1.16%gcc@4.8.5 arch=linux-rhel7-ivybridge
        ^expat@2.2.9%gcc@4.8.5+libbsd arch=linux-rhel7-ivybridge
            ^libbsd@0.9.1%gcc@4.8.5 arch=linux-rhel7-ivybridge
        ^gettext@0.20.1%gcc@4.8.5+bzip2+curses+git~libunistring+libxml2+tar+xz arch=linux-rhel7-ivybridge
            ^libxml2@2.9.9%gcc@4.8.5~python arch=linux-rhel7-ivybridge
                ^xz@5.2.4%gcc@4.8.5 arch=linux-rhel7-ivybridge
            ^tar@1.32%gcc@4.8.5 arch=linux-rhel7-ivybridge
        ^libffi@3.2.1%gcc@4.8.5 arch=linux-rhel7-ivybridge
        ^sqlite@3.30.0%gcc@4.8.5~column_metadata+fts~functions~rtree arch=linux-rhel7-ivybridge
    ^swig@4.0.0%gcc@4.8.5 arch=linux-rhel7-ivybridge
        ^pcre@8.42%gcc@4.8.5~jit+multibyte+utf arch=linux-rhel7-ivybridge
```

And we can see that CCTools doesn't directly depend on expat, but instead dependent on Python which depends on expat, so the best place to correct this problem either going to be in the Python or expat packages, which means we should raise an issue with the Spack people to correct this.

In the meantime, we could potentially work around this problem by having CCTools depend on expat directly, so we can get the right expat configuration in the CCTools package definition and circumvent the problematic part of the dependency tree.

**Comment by dthain** [comment]
@tjuedema I believe your instructions were incorporated into another pull.
Please check out master and see what's in there currently.
If the Spack install is working, then remove the comments and warning that suggest otherwise.

**Comment by dthain** [comment]
@btovar @tjuedema What's the status on this?
Did it get incorporated into a different PR?

**Comment by btovar** [comment]
It got incorporated in another one which follows spack standard installation. Also, see #2252

**Pull request closed without merging**
