### PR TITLE
Move old json.[ch] to Chirp module.

### PR DESCRIPTION
**Pull request by dthain**
Localizing this code to the chirp module, which is the last place it is used (extensively) in the `chirp_job` capability.  Everything else is now using JX for JSON support.  (Would be lots of work to update `chirp_job` to use JX with no external benefit.)

### CODE REVIEW

**Comment by dthain** [comment]
Not essential for 7.0

**Comment by dthain** [comment]
Any objections to merging?

**Comment by btovar** [comment]
Not as such, but there are conflicts with this branch.

**Comment by dthain** [comment]
Ok, let me take a look.

**Comment by dthain** [comment]
Rebased on master.

**Pull request merged**
