### PR TITLE
Add LDFLAGS for correct compilation

### PR DESCRIPTION
**Pull request by btovar**
To compile cctools on stampede:

CC=gcc CXX=g++ LDFLAGS='-fstack-protector' ./configure --without-static-libgcc

### CODE REVIEW

**Comment by dthain** [comment]
Is it realistic to consider providing instructions for a build gcc of perl/python?

**Comment by btovar** [comment]
Well, I am having trouble compiling parrot even with gcc. There seems to be a mismatch with the pthread library.

**Comment by btovar** [comment]
Ok, the problem for parrot seems to be the  -static-libgcc  flag.

**Comment by btovar** [comment]
With 

CC=gcc CXX=g++ LDFLAGS='-fstack-protector' ./configure --without-static-libgcc

all cctools can be compiled.

**Pull request merged**
