### PR TITLE
do not copy context on eval

### PR DESCRIPTION
**Pull request by btovar**
Fix for #2221

### CODE REVIEW

**Comment by trshaffer** [comment]
I think this might cause some issues with deltadb. The [calls to add builtins](https://github.com/cooperative-computing-lab/cctools/blob/master/dttools/src/jx_eval.c#L599) modify the context in place, which is fine for most of the uses of `jx_eval()` in the code. It looks like the added builtins would be observable during a checkpoint read in delatdb (and possibly when querying), which may cause other problems.

**Comment by btovar** [comment]
What about a jx_eval_closed_context for deltadb that copies the context and then calls jx_eval?

**Comment by trshaffer** [comment]
I would be more comfortable with a `jx_eval_inplace()` or something to that effect as a destructive version that's explicitly opt-in. For example, the command line tools like `jx2json` could switch to this version.

**Comment by trshaffer** [comment]
Another issue with 2 eval flavors: we already have both `jx_eval()` and `jx_eval_with_defines()`, so it'd be awkward to do every permutation (e.g. `jx_eval_inplace_with_defines()`). It might be better to split these up, i.e. we have a function

    jx_ctx_from_defines(struct jx *j, struct jx *context)

that replaces `jx_eval_with_defines()` but returns the resulting context object rather than doing the eval itself. Then the caller can choose which of the two eval flavors to use.

I can push commits for that to this PR if you like.

**Comment by btovar** [comment]
Tim, that sounds good! Thanks.

**Comment by dthain** [comment]
@trshaffer I'm a little uncertain about how functions are currently handled.

Would there be a serious downside to treating them more generically, by parsing SYMBOL ( args ) as a generic function call, and then just performing a simple string comparison at call time?

**Comment by trshaffer** [comment]
Not too serious. I was avoiding that as it's another weird case in `jx_eval_operator()` ([which is already sort of hairy](https://github.com/cooperative-computing-lab/cctools/blob/master/dttools/src/jx_eval.c#L338)).

But after looking at making changes in this PR, I'm thinking that lookup at call time might be the way to go.

**Comment by dthain** [comment]
That makes sense to me, and it also has the effect that
one can parse and print arbitrary function calls without
having a hard-coded list of acceptable names at parse time.

**Comment by dthain** [comment]
Thorough testing, as always...

**Comment by trshaffer** [comment]
I ended up doing a fair amount of internal changes, to remove the `JX_FUNCTION` type (see 7c3b9ca77bd7801816be9e2fc5c08791bf7cc57b for details). Since we've been adding statically defined functions as needed, there's not a whole lot of reason to keep internal support for full lambda functions. With this simplification/cleanup, we can avoid the expensive copy in #2221.

**Comment by trshaffer** [comment]
I was a bit concerned as there don't seem to be automated tests for DeltaDB stuff, but I don't see any issues from reading the code

**Comment by dthain** [comment]
@btovar what do you think?

**Comment by btovar** [comment]
Looks good to me.

**Pull request merged**
