### PR TITLE
Add docker doc for makeflow

### PR DESCRIPTION
**Pull request by charleszheng44**
1. Add note about Docker support at the beginning of the manual
2. Add Docker Support section

### CODE REVIEW

**Comment by dthain** [comment]
That's fine, but I meant the user manual: `doc/makeflow.html`

**Comment by charleszheng44** [comment]
I have edited doc/makeflow.html.

**Comment by dthain** [comment]
Um, no, what you have done here is to delete the user's manual and replace it with the man page.
Look at the commits carefully and try again.

**Comment by dthain** [comment]
Ok, now you have the right idea, but this pull now contains a sequence of commits that destroys and recreates `doc/makeflow.html`, which messes up the history.  Try again with a new pull that has one clean commit.

**Comment by batrick** [comment]
@charleszheng44 this PR needs fixed. You still have conflict markers in the documentation. Please look at:

`git diff master...ccl/pull/791/head`

and fix it.

Please also remove the merge commits. Do a rebase instead.

**Comment by charleszheng44** [comment]
Rebase the change onto master branch

**Comment by charleszheng44** [comment]
remove the merge junk in doc/makeflow.html

**Comment by dthain** [comment]
The docs are good as written (except for the three lines deleted) but please see @btovar or @batrick for some help on how to remove the master merges on this branch and get the pull request cleaned up.

**Comment by charleszheng44** [comment]
This pull request has been merged into #703

**Comment by dthain** [comment]
Superseded by #905

**Pull request closed without merging**
