### PR TITLE
vine: use number to represent a port in FuturesExecutor

### PR DESCRIPTION
**Pull request by JinZhou5042**
## Proposed changes

In the two test scripts for _futures_ we are using a list like `port=[9123, 9129]` to represent the port, but the constructor only accepts a number. 

## Post-change actions

Put an 'x' in the boxes that describe post-change actions that you have done.
The more 'x' ticked, the faster your changes are accepted by maintainers.

- [ ] `make test`       Run local tests prior to pushing.
- [ ] `make format`     Format source code to comply with lint policies. Note that some lint errors can only be resolved manually (e.g., Python)
- [ ] `make lint`       Run lint on source code prior to pushing.
- [ ] Manual Update     Did you update the manual to reflect your changes, if appropriate? This action should be done after your changes are approved but not merged.
- [ ] Type Labels       Select github labels for the type of this change: bug, enhancement, etc.
- [ ] Product Labels    Select github labels for the product affected: TaskVine, Makeflow, etc.
- [ ] PR RTM            Mark your PR as ready to merge.

## Additional comments
This section is dedicated to changes that are ambitious or complex and require substantial discussions. Feel free to start the ball rolling.

### CODE REVIEW

**Comment by JinZhou5042** [comment]
I am unsure how this change comes and what is the idea, should we change the test scripts or the constructor for _FuturesExecutor_? @BarrySlyDelgado

**Comment by JinZhou5042** [comment]
I don't know why this bug fails me just now when running `make test` but didn't affect the pr I proposed this morning ...

**Comment by btovar** [comment]
The port range should not be changed as otherwise the tests fail if port 9123 is already in use. If the range is not working in this case, then `FuturesExecutor` should be fixed.

**Comment by JinZhou5042** [comment]
Aha, I see! Should I go head and fix `FuturesExecutor ` so that it can select a usable port in that given range? @btovar

**Pull request closed without merging**
