### PR TITLE
vine: fix local-temp scheduling failure 

### PR DESCRIPTION
**Pull request by colinthomas-z80**
## Proposed Changes

Add a dedicated VINE_LOCAL_TEMP file flag to distinguish local temp files. 

## Merge Checklist

The following items must be completed before PRs can be merge.
Check these off to verify you have completed all steps.

- [x] `make test`       Run local tests prior to pushing.
- [x] `make format`     Format source code to comply with lint policies. Note that some lint errors can only be resolved manually (e.g., Python)
- [x] `make lint`       Run lint on source code prior to pushing.
- [x] Manual Update     Update the manual to reflect user-visible changes.
- [x] Type Labels       Select a github label for the type: bugfix, enhancement, etc.
- [x] Product Labels    Select a github label for the product: TaskVine, Makeflow, etc.
- [x] PR RTM            Mark your PR as ready to merge.

### CODE REVIEW

**Comment by dthain** [comment]
Hmm, this seems odd to me, can you explain this one in more detail?

I understand that you are substituting VINE_FILE objects for VINE_TEMP in the case where peer transfers can't be done.

And also that a task cannot run unless its input files have been materialized.

But if there is a bug for files-as-temp-substitutes, then isn't it also a bug for plain files used as intermediates in the normal way?

Also, `f->state == VINE_FILE_STATE_CREATED` should be a cheaper check than the system call `lstat`

Maybe I am missing something important here.

**Comment by colinthomas-z80** [comment]
Yes it seems that disabling peer transfers breaks the ability to use regular files as intermediates. As we will try to schedule them before the files have been created. I will fix that first.

**Comment by dthain** [comment]
Ah, so that problem isn't really disabling peer transfers per se, it has to do with checking input file states.

For a given task, *all* of its input files should be in `VINE_FILE_STATE_CREATED`.   And additionally, temporary files in that state should be checked to see if replicas still exist.

**Comment by colinthomas-z80** [comment]
Actually disregard the peer transfer causing the problem bit, but yes there is a bug

**Pull request closed without merging**
