### PR TITLE
Install instructions

### PR DESCRIPTION
**Pull request by btovar**
Updates install instructions.

### CODE REVIEW

**Comment by dthain** [comment]
So, judging from these install instructions, the draft Spack module does not yet set PATH, PYTHONPATH, and LD_LIBRARY_PATH.  But it could with some more work.  Did I get that correct?

**Comment by btovar** [comment]
Correct.

**Comment by btovar** [comment]
> So, judging from these install instructions, the draft Spack module does not yet set PATH, PYTHONPATH, and LD_LIBRARY_PATH. But it could with some more work. Did I get that correct?

Further, what we need is  `spack load cctools` to do that for us. `spack load` uses a modulefile which we still need to write.  I update the instructions with `spack load` accordingly.

**Comment by dthain** [comment]
Some suggestions for streamlining the instructions:

1 - This command seems scary to the un-initiated:
```
tar -C ~/cctools --strip-components=1 -xf cctools-*-source.tar.gz
```

While I get that you are trying to strip off the versioned directory string, I think that's likely to be confusing to the novice.  How about this more explicit approach?

```
tar xzf cctools-*-source.tar.gz
cd cctools-*-source
./configure
make
make install
```

2 - For the git install example, make it complete by adding the few lines of ./configure; make; make install

3 - Maybe drop the binary tarball section completely?

**Comment by btovar** [comment]
> Some suggestions for streamlining the instructions:

Done.

**Comment by btovar** [comment]
I think this is ready to be merged.
The only thing not working is spack, but it is marked appropriately.

**Comment by dthain** [comment]
Ben, are we ready to update the warnings on Spack, and move ahead?

**Pull request merged**
