### PR TITLE
standard error messages

### PR DESCRIPTION
**Pull request by btovar**
Address #1922

### CODE REVIEW

**Comment by btovar** [comment]
Ah, yes much better.

**Comment by dthain** [comment]
Also `printf("%s",str)` is safer than `printf(str)`

**Comment by btovar** [comment]
Corrected both.

**Comment by dthain** [comment]
The mantra for today is "merge it!"

**Comment by btovar** [comment]
Waiting for autobuild :)

**Comment by dthain** [comment]
Sorry, got a little excited.  :)

**Pull request merged**
