### PR TITLE
Poncho Analyze Format change

### PR DESCRIPTION
**Pull request by BarrySlyDelgado**
One issue is with channels. Each package is listed with as many channels there are.

### CODE REVIEW

**Comment by BarrySlyDelgado** [comment]
Looking for a solution to why the whole commit history appears when I make pull requests.

**Comment by dthain** [comment]
Suggest that you get back to a fresh state like this:
```
# drop changes in progress on the current branch
git checkout -f
# go back to the master branch
git checkout master
# pick up the latest changes from origin
git pull --rebase origin master
# start a new branch:
git checkout -b poncho-analyze-something
```

**Comment by dthain** [comment]
And since the spec file format has changed, make sure to update the relevant parts in `doc/manual/poncho/index.md`

**Comment by BarrySlyDelgado** [comment]
I believe you have a pull request with doc changes. Is it best to merge that first?

**Comment by dthain** [comment]
Yes

**Pull request merged**
